### PR TITLE
had enough of the sex chems

### PR DESCRIPTION
**Pull request by chemistrymain2**
people cannot behave maturely with them and the content prefs are off, so if we're going to have ZZ cup women running around

a. i deliberately code in worse shit than ever beore

b. i remove it

pick one

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
I suggest deleting both the enlargement.dm's since you deleted all their contents their empty now.

**Comment by NX115** [comment]
No. Just because you don't like it doesn't mean it should be removed.

**Review by NX115 — COMMENTED** [review]
Please grow up and realize you are in rapistlrp town, kthx.

**Review by NX115 — CHANGES_REQUESTED** [review]
Requesting that this entirely fucks off.

**Review by BadAtThisGame302 — APPROVED** [review]

**Comment by Zebraman** [comment]
Make it so if your bits grow to retarded size it rips your armor and pants off and kills your from bloodloss like it used to. Add some brain damage too because why not.

**Comment by LocalizedDownpour** [comment]
Incredibly based PR.

**Comment by SeeminglyTypicalUsername** [comment]
remove le sex chems

**Comment by Weaselburg** [comment]
Thank you frok, very cool.

**Comment by Serxule** [comment]
cope

**Comment by Serxule** [comment]
also just re-add content prefs like

**Comment by ogrigbe** [comment]
I haven't seen it abused too much. However if I see more of the fuckery that comes from it then I will air to have it removed. I agree with both sides. It can be LRP and abused but at the same time people are probably enjoying it? I don't really pay attention to the people who do things with it beyond the memes...we'll see and move from there okay?

**Comment by NX115** [comment]
> also just re-add content prefs like

Bet. I'll also add combat & ghoulification prefs.

**Comment by Kitsunemitsu** [comment]
Combat isn't performing nonconsensual sexual acts on someone.

Just because you like it doesn't mean that other people are abusing it to make people uncomfortable.

**Comment by SaintPhilosopher** [comment]
Reopen PR and remove it. I refuse to participate in someone's sexual fetish RP.

**Comment by Serxule** [comment]
> Reopen PR and remove it. I refuse to participate in someone's sexual fetish RP.

this is why i said readd content prefs

**Comment by chemistrymain2** [comment]
> > Reopen PR and remove it. I refuse to participate in someone's sexual fetish RP.
> 
> this is why i said readd content prefs

No. I am removing it from the game entirely, because I _prefer_ that it does not exist.

**Pull request closed without merging**
