### PR TITLE
Den Shrink PR+Shop Removal

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

The Den lost its shop out of serious outcry. They keep their vendor. The Den now has an "entertainment" building to their south and a pretty pond. The focus is now on the casino to facilitate gimmicks,
image

There is a lil dungeon to the east that requires mining tools now.

## Why It's Good For The Game

No longer Oasis 2,

## Pre-Merge Checklist

- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

:cl:
tweak: tweaked a few things
balance: rebalanced something
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
image
This is the current map as it stands.
Any feedback is appreciated.

**Comment by ZAB909** [comment]
i really think the den should have a shop. Like a black market. The difference being you will also probably be mugged or robbed, cause its a shady gambling underground ring. That's what used to make it unique. It shouldnt be what Oasis has, but their own, like gang weapons from the spawner, obv way less materials/bps than Oasis has

**Comment by BadAtThisGame302** [comment]
> i really think the den should have a shop. Like a black market. The difference being you will also probably be mugged or robbed, cause its a shady gambling underground ring. That's what used to make it unique. It shouldnt be what Oasis has, but their own, like gang weapons from the spawner, obv way less materials/bps than Oasis has

I personally think drugs/casino will make the Den more unique in a way, since if they have a shop they'll have to have the same things Oasis sells, so cutting that off and moving toward a new income system for them is big.

**Comment by ZAB909** [comment]
> > i really think the den should have a shop. Like a black market. The difference being you will also probably be mugged or robbed, cause its a shady gambling underground ring. That's what used to make it unique. It shouldnt be what Oasis has, but their own, like gang weapons from the spawner, obv way less materials/bps than Oasis has
> 
> I personally think drugs/casino will make the Den more unique in a way, since if they have a shop they'll have to have the same things Oasis sells, so cutting that off and moving toward a new income system for them is big.

I agree that drugs and having an other chemical maker that isnt followers for cool sus shit for wasters is fun. But I think having a base faction that is another shop, is good. Cause having a singular place that is a dedicated shop isn't  cool, and having a seedy underground blackmarket is awesome and makes sense in the post nuclear world. It adds another player faction to sell loot to. I don't think they should just be a crafter like Oasis, but more of a merchant. A gang that sells shady drugs will also have SOME weapons, because if  youre making drugs, you need to defend them, probably.

**Comment by AllCorruptingWyrm** [comment]
so
the Den Shop was more filler. I want to see how the vendor works in stay of the Shop. I'm looking into slot machines at the moment so we'll see how that goes. The Den's niche is explosives and the selling of gimmick items i.e throwing stars and the such. The Khans deal in drugs and stuff like that so I don't wanna step on their territory here.

**Comment by BadAtThisGame302** [comment]
> so
> 
> the Den Shop was more filler. I want to see how the vendor works in stay of the Shop. I'm looking into slot machines at the moment so we'll see how that goes. The Den's niche is explosives and the selling of gimmick items i.e throwing stars and the such. The Khans deal in drugs and stuff like that so I don't wanna step on their territory here.

So.. remove Khans and make the Den deal in drugs as well as casinos... 🤯

**Comment by ZAB909** [comment]
Khans are dumb. I thought these dudes make the drugs for the wasters, now?

**Comment by AllCorruptingWyrm** [comment]
> > so
> > the Den Shop was more filler. I want to see how the vendor works in stay of the Shop. I'm looking into slot machines at the moment so we'll see how that goes. The Den's niche is explosives and the selling of gimmick items i.e throwing stars and the such. The Khans deal in drugs and stuff like that so I don't wanna step on their territory here.
> 
> So.. remove Khans and make the Den deal in drugs as well as casinos... 🤯

Never happening. Rigbe said he refuses to remove any factions.

**Comment by AllCorruptingWyrm** [comment]
image
current map

**Comment by AllCorruptingWyrm** [comment]
image
Up to date photo.

**Comment by Serxule** [comment]
the shop is literally the only reason why people go to the den, not to mention khans _already_ are the drug making faction, i dont see how a casino would even be fun either

**Comment by AllCorruptingWyrm** [comment]
> the shop is literally the only reason why people go to the den, not to mention khans _already_ are the drug making faction, i dont see how a casino would even be fun either

In due time it'll be RNG casino slot machines that will make people go there
also
Den have explosives, also, I was told to remove the Shop so take it up with the community at large, the Shop that existed was stand in to test how effective selling bombs and other niche items would be.

**Comment by AllCorruptingWyrm** [comment]
image
final map

**Pull request merged**
