### PR TITLE
Moved enclave base

### PR DESCRIPTION
**Pull request by ZAB909**
Moved enclave surface base to under the vault dungeon
Being so close to legion was cringe
fixed a few tiles from my legion camp PR

## About The Pull Request

---Enclave Bunker---
before: https://imgur.com/a/cSxlJs2
after: https://imgur.com/a/rnPoEoi

added:

Timed doors to the west that open at 30 mins. So they cannot dungeon rush the raiders by mining west and ignore the nightstalkers

removed random melee loot
a stim
a shrap mine
more sandbags and wooden cades
a bowie knife
low tier ballistic gun

mobs
2 nightstalkers
nightstalker nest
3 rad roaches
roach nest

---Previous location---

Decreased cave size somewhat

Has a young and a mature night stalker
night stalker nest
random melee loot
a med ballistic
1 tier 2 ammo
1 tier 3 ammo

after: https://imgur.com/a/qo56QSl

---Highway Tunnel---
added 2 raiders
replaced hobo ballistic with low-med
1 tier 2 ammo
quite a few barricades
1 healing powder

Before: https://imgur.com/a/82u6Zg7
after:  https://imgur.com/a/rnPoEoi

---Collapsed Legion tent area building---
I forgor to update the above map in my legion camp PR to account for the ruined foundation. Also cleaned up a singular road block that was misalligned
A single table has fallen down and landed on the ground below

After: https://imgur.com/a/CTNt7BE

## Why It's Good For The Game

2 major faction bases are no longer within 10 tiles from each other. Awesome.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
the
/:cl:

### CODE REVIEW

**Comment by Egorium** [comment]
Remove nests

**Comment by ogrigbe** [comment]
Enclave base is fine where its at right now.

**Comment by ZAB909** [comment]
You said that you wanted to move the enclave base, in discord https://imgur.com/a/tA0QaL4
If you don't want to feel free to close da funny PR, don't wanna unfuck the conflicts if it's not what ya want anyway.

**Comment by ZAB909** [comment]
Enclave base was already moved, and I think it's a better location as well

**Pull request closed without merging**
