### PR TITLE
Finally... the Khans are gone...

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Replaces the Khans with the Powder Gangers. The Powder Gangers are probably going to be more fun, more interactive and more "neutral"

## Why It's Good For The Game

Khans have been a bad faction since DR. They rarely interact with anyone else but themselfs, they are meant to do SOME robbing but instead they sit in their base and do nothing all the day, unless the Legion asks them to raid the NCR which they eagerly accept for "Bitter Springs" 

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added a "unique" powder ganger NCRCF Vest
del: Removed the Khans and replaced them with the Powder Gangers
fix: fixed everything having the name Khans to Powder Gangers
/:cl:

### CODE REVIEW

**Comment by panzerr1944** [comment]
lmao. powder gangers are going to be the exact same as khans except they have more reason to valid people as they're generic convicts with no out-of-region bases. khans are unironically fine as they are.

**Comment by AllCorruptingWyrm** [comment]
stop coping because you got robusted once.

**Comment by cornercube** [comment]
i would recommend testing the dynamite, last i checked it made a beep noise instead of a hiss

**Comment by thart02** [comment]
Yeah i'm gonna have to say this is cringe

**Comment by SeeminglyTypicalUsername** [comment]
Based powder gangers

**Comment by ogrigbe** [comment]
i said no

**Pull request closed without merging**
