### PR TITLE
Buffed SuperSledge

### PR DESCRIPTION
**Pull request by Seraphim-Hub**
## About The Pull Request

* Update f13twohanded.dm
Increased Damage value by Twenty to make up for the power difference between it and other options.

## Why It's Good For The Game

The natural ratio of paladin class selection is dominated by the minigun & AER, this buff should increase enjoyability, selection, & use of the close quarters paladin set and the Super Sledge in general.

## Pre-Merge Checklist

- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

### CODE REVIEW

**Comment by chemistrymain2** [comment]
No.

**Comment by LocalizedDownpour** [comment]
Are you high? 80 damage? What about the Vet Decanus that ALSO gets a Super Sledge? Meaning he'd have a 100 damage weapon with Big Leagues.

**Comment by BadAtThisGame302** [comment]
Based?? Your first PR is a super sledge buff??

**Comment by Serxule** [comment]
jesus christ

**Comment by ogrigbe** [comment]
I think it'd be a bit much with the current state of big leagues, buffout, berserker powder etcetera. 80 is a bit much to get hit in the head with considering I bet that's a two hit crit through a great deal of armors.

**Comment by LocalizedDownpour** [comment]
> I think it'd be a bit much with the current state of big leagues, buffout, berserker powder etcetera. 80 is a bit much to get hit in the head with considering I bet that's a two hit crit through a great deal of armors.

With big leagues alone it's a flat 100 damage. This will 2hit crit any armor at 50 and below for melee resist. Three hit for literally anything else.

**Pull request closed without merging**
