### PR TITLE
Fix chemicals ya

### PR DESCRIPTION
**Pull request by Kit8Bit**
## About The Pull Request

I've made all mentions of spewium into comments so they shouldn't show up in-game anymore. Even if they do, hopefully they won't do anything.

## Why It's Good For The Game

Spewium has been being abused by players to stunlock players in place using chemical tomatoes with gaseous decomposition to make a grenade that explodes into a cloud of spewium upon impact. These clouds of spewium lock players into a loop of vomiting, preventing them from moving and doing anything at all. Hopefully with this removed, factions like the Enclave won't be able to abuse these to get an unfair advantage again.
## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog

:cl:
del: Removed spewium
/:cl:

### CODE REVIEW

**Comment by Hadoje** [comment]
It was very funny while it lasted

**Comment by Legate-Maxson** [comment]
so uh are these not countered by gasmasks?

**Comment by Legate-Maxson** [comment]
Spewium isnt even the chemical they used. Looking at logs they used sludge this PR doesnt do anything since you can counter this with gas masks.

**Comment by Kit8Bit** [comment]
> Spewium isnt even the chemical they used. Looking at logs they used sludge this PR doesnt do anything since you can counter this with gas masks.

Cool, so you're going to ban it then?

**Pull request closed without merging**
