### PR TITLE
Resprites the secborg

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

Secborg goes from this:

image

To this:
image

(also makes a minor change to the police baton)

## Why It's Good For The Game

Things looking good is good

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by ZAB909** [comment]
blue is cooler than green so 1+

**Comment by Sinbest** [comment]
I tried to give him a hat or a badge or something but it looked like shit, oh well.

**Comment by ZAB909** [comment]
Maybe add the same kinda battle scar/scratches the green old one has, to break up the single colour of blue.

**Comment by Sinbest** [comment]
> Maybe add the same kinda battle scar/scratches the green old one has, to break up the single colour of blue.

Those aren't battle scars, they're meant to be the star and writing that's on gutsys

**Pull request merged**
