### PR TITLE
Small Item Update

### PR DESCRIPTION
**Pull request by Altum21**
## About The Pull Request
Added the following items 
Uniforms 
tracksuit (meant to be a super rare spawn)  *goes along with the scav set i added last update*
enclave_exile 

Suit
Bandit_duster (meant to be a super rare spawn) 
enclave_seva (For any donater) *based off of monolith seva suit from stalker*
altumt51 (For me)

Head
enclave_sevahead (For any donater) *based off of the monolith seva suit from stalker*
altumt51helm (For me)
drillhat (For me)

## Why It's Good For The Game
more stuff gets added, everyone lives laughs loves 

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
I'll just fix this again like before, actually.

**Comment by Altum21** [comment]
> I'll just fix this again like before, actually.

no dont fix it, its okay its great

**Comment by BadAtThisGame302** [comment]
Well it's not and you'll probably cause issues with T-51b if this gets merged.

**Comment by Altum21** [comment]
> Well it's not and you'll probably cause issues with T-51b if this gets merged.

I tested it and it should be fine. Reason why the helmet doesn't share code and has its own values is because it gave issues with turning on the helmet light. It should all be good. If there is a problem please point it out so I can learn and improve 🙏🙏

**Comment by BadAtThisGame302** [comment]
> > Well it's not and you'll probably cause issues with T-51b if this gets merged.
> 
> I tested it and it should be fine. Reason why the helmet doesn't share code and has its own values is because it gave issues with turning on the helmet light. It should all be good. If there is a problem please point it out so I can learn and improve 🙏🙏

I did comment on plenty of the things that are wrong, but this was merged anyways LOL.

**Pull request merged**
