### PR TITLE
Fallout Alien Content

### PR DESCRIPTION
**Pull request by ishitbyabullet**
## About The Pull Request

A long time ago, around 2019 or so, there was a server called Vault 113 Restoration by PahomLancer. Around this time, I was pissed off by how every fallout 13 server never fucking adjusted the abductors to be more fallout-like, so me and him fixed that by recoloring the abductor and using /vg/station alien space suit outfit. Apparently no other server ever stole this, so I am PRing it again.

**There are some things to be noted:** 
- The vest's item/ground icon is an error despite repeated attempts to fix it, but I decided not to worry about it too much since this is basically admin-only gear. 
- The abductor agent, if ever spawned, now has the alien blaster gun and two cells. This fits more than the abductor gun, and he'll only have 12 shots without admin assistance.
- They now have satchels and no abductor jumpsuits due to reasons stated in the code.

## Why It's Good For The Game

Why are the Fallout aliens not Fallout themed?

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
tweak: Abductors now have more of a Fallout theme.
fix: Abductors can now shoot the alien blaster. Bit of an oversight, eh?
/:cl:

### CODE REVIEW

**Comment by OliOliOnsiPree** [comment]
Photos?
👀

**Comment by ishitbyabullet** [comment]
> Photos? eyes

ayy lmao
image
image

**Comment by chemistrymain2** [comment]
good

**Comment by ogrigbe** [comment]
ack ack

**Comment by ZAB909** [comment]
Based and ayylmao pilled.

**Pull request merged**
