### PR TITLE
Add flash protection to pilot goggles.

### PR DESCRIPTION
**Pull request by NX115**
Add vision correction to pilot goggles.

## About The Pull Request
Add vision correction to pilot goggles.

## Why It's Good For The Game
Keeps enclave members from having to select between glasses and goggles.

## Pre-Merge Checklist

- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog

:cl: NOXA| Yuan-SunWei| Luana|SABRIAH
add: Adds vision correction to pilot goggles
/:cl:

### CODE REVIEW

**Comment by Weaselburg** [comment]
Why are you giving night vision googles flash protection, exactly?

And 'Heat Sensitive' doesn't mean flash resistant. It means its MORE SENSITIVE to it.

**Comment by NX115** [comment]
> Why are you giving night vision goggles flash protection, exactly?
> 
> And 'Heat Sensitive' doesn't mean flash resistant. It means its MORE SENSITIVE to it.

/obj/item/clothing/glasses/night/f13/enclave
has no lighting_alpha changes. The item directly above it does. Hence I didn't think to check that its parent /glasses/night would have night vision. So, yeah, I didn't know.

**Comment by Serxule** [comment]
enclave has flash-proof masks (Unless the descriptions wrong) and also the welding eyes implant

**Comment by BadAtThisGame302** [comment]
What a salt PR man, Jesus Christ.

**Pull request merged**
