### PR TITLE
Disables the robotics control console in R&D systems until somebody makes it balanced

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

See above.

Disables the robotics console until somebody can code it to not be a griefers dream.

## Why It's Good For The Game

At the moment one robotics console can destroy all the cyborgs in Yuma, regardless of faction, this is unbalanced and not fun for everybody evolved.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Legate-Maxson** [comment]
No. As long as borgs exist in the server the Console is necessary to stop griefing from all access borgs the enclave and BOS keep making. If you want an actual reason to remove it recode borgs not to have all access by default. This will not be added.

**Comment by chemistrymain2** [comment]
As Raptor said, hard no. I presented you with an alternative solution, you pretended it didn't exist, then you said you weren't a coder so you weren't going to do it.

You made this PR because you died as a cyborg while raiding the BoS.

**Comment by Sinbest** [comment]
>

Ignoring the fact that this is objectively false, I think that being able to randomly blow up cyborgs across the map is bad.
Also, your "alternative solution" was repeating somebody else's "alternative solution" and demanding I do it despite having almost no coding experience.

Why didn't _you_ offer to do it until after my PR was up? Strange.

**Comment by Sinbest** [comment]
> No. As long as borgs exist in the server the Console is necessary to stop griefing from all access borgs the enclave and BOS keep making. If you want an actual reason to remove it recode borgs not to have all access by default. This will not be added.

How does being able to grief cyborgs which across the map by making them blow up "stop griefing"?
If you are referring to doors, if you can't destroy a cyborg which is **within viewing distance**, that sounds like a skill issue to me.

**Pull request closed without merging**
