### PR TITLE
Enclave changes, Balance changes

### PR DESCRIPTION
**Pull request by Legate-Maxson**
oh boy time for screaming

**NCR CHANGES:**
reduced some NCR armor Numbers to what they were SUPPOSED to be before someone added plating to alot of them and standardized the two Captain armors.

Veteran ranger brush gun loadout, Now comes with a primer.

Trail ranger armor now has wound protection so it can be used.

**LEGION CHANGES:**

Centurion loadouts changed due to community outcry. 

Palacent slow down increased.
It now loses the Goliath and gets the m1919 like before, still has CQC

Warlord Paladin loses the m1919 in exchange for Goliath and 14mm pistol 

Scout ambusher loadout now gets a funny shotgun in its backpack because frok said so.

We had a legion vex helmet floating around and a really well known vex was having his CQC book replaced by admins for a new loadout book, so I made it a separate loadout.

_Night Stalker Vex:_ Neo-Russian primer and a trail carbine enjoy the new vex long range class.

**BOS changes:** 

Knight armors slightly buffed.

**Enclave changes:**

NEW ROLE : Enclave Armored Infantry

APA was removed from the Gunny SGT and placed onto this role that has the choice between two heavy weapons the Minigun and the Gatling laser.

Gunny SGT: Completely reworked. Now gets Marine Armor and hard yards, Losing all PA training it had. Has a choice between two loadouts a melee loadout and an ranged loadout.

The main reason for this change was protag syndrome to many times did the second in command leave the bunker wordlessly to play masterchief in the wild only for a recruit legionnaire to beat there ass to death with a fire axe. Now you don't lose your APA soldier and SECOND IN COMMAND when they chose to wander off wordlessly.

Swat armor slightly buffed. Still horrid against melee but now has better laser resistance.

New Sprites as seen below. 
 
unknown

### CODE REVIEW

**Comment by LocalizedDownpour** [comment]
We have marine armor in the code! The Sprite is Good! Why can't we USE IT!

**Comment by Legate-Maxson** [comment]
This is the sprite the colors was just darkened

**Comment by LocalizedDownpour** [comment]
> This is the sprite the colors was just darkened

/obj/item/clothing/suit/armor/f13/usmcriot This

**Comment by panzerr1944** [comment]
> > This is the sprite the colors was just darkened
> 
> /obj/item/clothing/suit/armor/f13/usmcriot This

too much riot armour in game at the moment. cope and have unique armour that is cool.

**Comment by Legate-Maxson** [comment]
> > This is the sprite the colors was just darkened
> 
> /obj/item/clothing/suit/armor/f13/usmcriot This

haha no, We are not having the 8th clone of Veteran ranger combat armor. Were actually having Marine armor from a more recent game

**Comment by panzerr1944** [comment]
reopen it you actual goob.

**Comment by BadAtThisGame302** [comment]
> > > This is the sprite the colors was just darkened
> 
> > 
> 
> > /obj/item/clothing/suit/armor/f13/usmcriot This
> 
> 
> 
> haha no, We are not having the 8th clone of Veteran ranger combat armor. Were actually having Marine armor from a more recent game

So remove it from the game.

**Comment by Legate-Maxson** [comment]
> 

I did and you know what's funny? I had to readd it because someone put it on sunnydale :)

**Comment by ishitbyabullet** [comment]
Just give the enclave/bos more power armor in general tbh. Everyone brags about being able to kill them in 3 hits anyways, it's not like you'd be giving out godmode.

**Comment by AllCorruptingWyrm** [comment]
no.

**Comment by CaputCapital** [comment]
"The main reason for this change was protag syndrome to many times did the second in command leave the bunker wordlessly to play masterchief in the wild only for a recruit legionnaire to beat there ass to death with a fire axe. Now you don't lose your APA soldier and SECOND IN COMMAND when they chose to wander off wordlessly."

Theoretically:
>APA wanders off in dustbowl alone and gets ganked
>Gunnery Sergeant is still alive and totally nothing bad can happen right after right?
>APA inquisitor fucks up Gunnery Sergeant

You tried, Legate-Maxson.

Frok's reduction on slots doesn't make this any better.

**Pull request merged**
