### PR TITLE
Legion cent + vex buff.

### PR DESCRIPTION
**Pull request by BobNewman-max**
## About The Pull Request

Gives cent the new nerfed CQC, just remember to merge the CQC nerf PR first. It exists. Its cool. Very epic. 

Gives vex the goliath. 

Lets see how this goes.

## Why It's Good For The Game

Gives legion some round-start ability to fight other factions. (fighting the NCR all day is boring.) 

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Well, two things:

First of all: You don't even give the Vex the Goliath.

Second: Your entire reason of adding back an overpowered CQC (No matter how much you nerf it unless you make it worthless) is "countering other factions" which, the Legion WILL never do and ever RARELY did when they had CQC, this will just be used as another reason that NCR mains will cope that the Legion's just, plainly better than them. Because let's face it, CQC was removed for a reason, no matter how much you "remove OP aspects of CQC" it'll still be a very good martial art that has basically no drawback, like berserker did.

**Comment by gilvian** [comment]
if vex gets a goliath why can't brotherhood paladins get a power fist?????????????????????????????????

i want initiates with cqc

**Comment by BobNewman-max** [comment]
> if vex gets a goliath why can't brotherhood paladins get a power fist?????????????????????????????????
> 
> i want initiates with cqc

Do it. I see 0 issues with the power fist going to the brotherhood. Thing is, I hate the factions players and want the faction removed. So no. I won't buff the BoS.

Legion has shit players but they occasionally get better. So yeah. Lets add it.

**Comment by BobNewman-max** [comment]
> Well, two things:
> 
> First of all: You don't even give the Vex the Goliath.
> 
> Second: Your entire reason of adding back an overpowered CQC (No matter how much you nerf it unless you make it worthless) is "countering other factions" which, the Legion WILL never do and ever RARELY did when they had CQC, this will just be used as another reason that NCR mains will cope that the Legion's just, plainly better than them. Because let's face it, CQC was removed for a reason, no matter how much you "remove OP aspects of CQC" it'll still be a very good martial art that has basically no drawback, like berserker did.

I did indeed forget to give it to the vex thanks for reminding me. 

Back on topic though, no it isn't my ONLY reason. Also, it had a drawback? you know how you had to get within MELEE RANGE? yeah. Thats a pretty big drawback. The NCR as a faction malding due to skill isn't a reason to NOT add things into the game as well. If the NCR keep getting skill issued, fuck them. Not a joke. If you are a player and all you do is complain about the other faction being more powerful when YOU should know, NCR is currently the most OP fucking faction around?

Then fuck yourself. I don't care who will go ape at me. Legion deserve to be balanced against all factions. Not just the NCR. 

This PR is mainly happening because as Enclave APA. I was able to wipe the legion out with nothing but APA, 1 mace glove, empty hands. I had a shishkebab but didn't even use it. Because I didn't need to. Thats my point. Legion have no real counters to PA users atm apart from throwing spears which you can easily catch in combat.

As for CQC getting removed. The reason it was removed was due to salt. I was the cause of both scenarios and can confirm, most of the fights I won with CQC. I won simply due to the player I was fighting going ape and running into a fucking wall or losing their stamina.

And I'll end it on the main point, CQC being OP. There are a LOT worse things then CQC. Want me to break those so you can call them OP as well? Because if the claim of OP is all it takes. I'll give you a LOT of OP shit then. Just for you babe B)

CQC Isn't OP. Stop coping.

**Pull request closed without merging**
