### PR TITLE
removes the enclave

### PR DESCRIPTION
**Pull request by gilvian**
fuck em
## About The Pull Request
Everyone keeps talking about removing the followers so I'm removing the enclave.
image
top is now a bigger cave, perfect for tribals to settle in
image
Mine is now bigger and has a bunker at the end with few supermutants and a deathclaw.

## Why It's Good For The Game
Enclave bad
## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
del: Removed enclave
server: most likely will make me gitbanned
/:cl:

### CODE REVIEW

**Comment by Sinbest** [comment]
nah

**Comment by BadAtThisGame302** [comment]
Why did you spend so much time on this PR, even though it'll be declined?

**Comment by gilvian** [comment]
> Why did you spend so much time on this PR, even though it'll be declined?

it took me entire 13 minutes

**Comment by BobNewman-max** [comment]
straight up? Yeah its funny. Do it for a week, see how the server changes. Then go from there. I think this should be done once for all factions, remove them for a short while, see how it effects the server, add it back. Compare the difference. No. I'm not joking. Do it.

**Comment by DelineFortune** [comment]
Sure, yes please. Enclave is doing nothing good for server. They are just killing people without esc

**Comment by Sinbest** [comment]
> Sure, yes please. Enclave is doing nothing good for server. They are just killing people without esc

player issue

**Pull request closed without merging**
