### PR TITLE
removes the deathclaw gauntlet from legendary claws

### PR DESCRIPTION
**Pull request by chemistrymain2**
image

more seriously, deathclaws shouldn't drop this shit

### CODE REVIEW

**Comment by 5467543** [comment]
the gauntlet is fine, the fact that it drops from claws is fine, there's just too many legendary claws, replace them with mothers instead and then port it

**Comment by BadAtThisGame302** [comment]
> the gauntlet is fine, the fact that it drops from claws is fine, there's just too many legendary claws, replace them with mothers instead and then port it

Legendary's are I think the most feared claws, most the people I have seen fight dclaws have died to legendary's. I think this is a good change due to putting most claws to mothers will make things easier dungeon wise, at least in my opinion.

**Comment by panzerr1944** [comment]
just turn down the probability or swap the legendary spammed claws with mothers, so theres less of them

**Comment by 5467543** [comment]
> > the gauntlet is fine, the fact that it drops from claws is fine, there's just too many legendary claws, replace them with mothers instead and then port it
> 
> Legendary's are I think the most feared claws, most the people I have seen fight dclaws have died to legendary's. I think this is a good change due to putting most claws to mothers will make things easier dungeon wise, at least in my opinion.

yesterday I killed six of them back to back with a spear, a trekking book, and a single stim
they aren't hard to kill provided you aren't a moron, they just take longer

**Comment by ZAB909** [comment]
Imo either making it like a 25% chance to spawn on legendaries or just put the spawn on mother claws. Or even better both. You deserve to get SOMETHING from killing a legendary claw.

**Comment by ogrigbe** [comment]
change the chance to like 20% please instead of removing it.

**Pull request closed without merging**
