### PR TITLE
NCR Camp Miller Update

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
Bunks in camp miller are now named for NCOs, and they spawn in their bunks.
Renamed the bunks in the northwest of the base, and the armory is now renamed to the Logistics Office.

The dress jackets are no longer all Commissioned officer ones (IDK who did this, but they did) and commissioned officers now have their personal dress equipment, while the enlisted all share.

While corporals having their own bunks isn't true to life, there are actually so many private slots that they fill all the beds, and the corporals could have their own place, reasonably.

## Why It's Good For The Game
The NCR has just gotten a base update that is generic. I think that having NCOs with their own bunks is a good idea, while all the privates bunk together. 

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: turned the northwest bunks into NCO bunks
tweak: turned the old sergeant bunks into an officer bathroom
tweak: added commissioned officer dress jackets and hats to their cabinets
tweak: turned the armory office into a full LO office
fix: replaced all the commissioned officer dress lockers with enlisted ones
/:cl:

### CODE REVIEW

**Comment by Kitsunemitsu** [comment]
I can change any of this, just ask instead of closing.

**Comment by SeeminglyTypicalUsername** [comment]
pictures pls

**Comment by Kitsunemitsu** [comment]
Yeah, one sec!

**Comment by Kitsunemitsu** [comment]
downstairs
upstairs

**Comment by BadAtThisGame302** [comment]
> downstairs upstairs

Looks good

**Comment by DaemonTinadel** [comment]
Why was this PR pushed through? You've the made the NCR practically unraidable and gave them a big fuck off gate. It's 
a cool flavor of life addition but did you think of how this would affect raiding or fighting?

**Comment by githubuser4141** [comment]
I love there's a upper Z-level, FO13 hasn't had multiple Z-levels before and a lot of the map hasn't been adjusted yet.

**Comment by Kitsunemitsu** [comment]
Guys I didn't fucking
Change anything aside from move spawns around and added in a bathroom.
Read the CL

**Pull request merged**
