### PR TITLE
Khanbackupdated

### PR DESCRIPTION
**Pull request by OliOliOnsiPree**
## About The Pull Request

Basically tweaks the back of the khans, with seeds + spaceman suit gimmick crates. These crates are to help when a boring round turns into 😴 and can help with gimmicks of the current rounds for the khans. Upgrades the imitation stims to regular stims, only two however. Basically adds seeds seeds seeds to make drugs and meds, with an static cave shroom spawn. 
image

Alright now the fun part. This also adds the den store back, but this time without upgrading anything, like giving them anything as they needed a gimmick and a store is a good gimmick for them to sell the things much like a open black market in a sense but the catch is you gotta get all the gear yourself. Nothing much else was added here, and also gives the den upgraded drink dispensers, only one spot. Image below
image
image

## Why It's Good For The Game

This is good for the game as it is more quality of life and gives more life for the khans in the back especially because it makes a tad bit more easier plus more things to make ALLL the drugs with. 
Den upgrades and tweaks is for the faction to thrive more on its own rather then TDM TDM TDM TDM!!

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: khans back with seeds + spacesuit + colormate board.
add: Den store back + upgraded drink machines
/:cl:

### CODE REVIEW

**Comment by ishitbyabullet** [comment]
That's an alien space suit, not a normal space suit.

**Comment by BadAtThisGame302** [comment]
Didn't we remove the Den shop for a reason? Why is it being re-added?

**Comment by OliOliOnsiPree** [comment]
> 

fixed it.

**Comment by OliOliOnsiPree** [comment]
> Didn't we remove the Den shop for a reason? Why is it being re-added?

I was talking to Tzula who reimplimented it and they said it was fine basically readding it back, as they need an gimmick other then an casino in a sense and its a small post, more for like blackmarket in a sense, so thats why its really small and if you are an den player or den main you can sell the loot far easier from the store area.

**Pull request merged**
