### PR TITLE
Mechs update/rebalance

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

- Increases health of all mechs.
- Increases damage on ranged mech weapons and reduces armor penetration on them.
- Reduces melee knockdown from mechs.
- Minor code improvements(?).

## Why It's Good For The Game

- Mechs were built for /tg/ weapon balance, not for F13 60 damage melee stuff.
- Same as above - makes weapons deal damage similar to what other F13 weapons do.
- Makes melee fighting mechs less frustrating, stun was reduced by a lot.
- Attack sound and knockdown time is now a variable.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by githubuser4141** [comment]
AFAIK the mecha "BR" missile is a bullet/projectile that only _explodes_ when it hits a sturdy target, otherwise it still does it's regular damage/AP. So I'm somewhat confident it's now a 200 damage 'gun' that holds 6 rounds. As for the runtime, try walking forward when shooting a mech projectile gun (any non-hitscan/grenade mech gun.) There's a chance the bullet will get stuck behind the mech where it'll stay generating runtimes.

**Comment by EgorDinamit** [comment]
> AFAIK the mecha "BR" missile is a bullet/projectile that only _explodes_ when it hits a sturdy target, otherwise it still does it's regular damage/AP. So I'm somewhat confident it's now a 200 damage 'gun' that holds 6 rounds.

Oh, if it's the case I'll change the damage back.


> As for the runtime, try walking forward when shooting a mech projectile gun (any non-hitscan/grenade mech gun.) There's a chance the bullet will get stuck behind the mech where it'll stay generating runtimes.

Eh, seems like a general issue with almost every gun even as human. Frok got projectiles port going, so it'll probably be fixed.


> Also.. 800 health for a Durand that can strafe is uh.. rather tough. It's tougher than the Marauder (which cannot strafe, and is also slower) which is odd because the marauder's sprite suggests it's a lot.. 'bulkier', IMHO the Durand's durability should come from it's energy shield rather then raw HP.

I guess. My idea was to make it so Duran has more health but can't really fight, whereas Marauder is basically a death sentence with less HP. I can change it around a bit.


> P.S. If you know anything about the topic limiter, could you check why mechas are causing some or all users to exceed the topic limits when using them? I'm not certain if it happens to everyone but I've seen myself and a few others have this issue, from what I've seen it's exacerbated when using slow mechs and by high time dilation.

Sorry,  I can't fix time dilation. There might be a PR lying on /tg/ somewhere that solves it, but for now, we'll just have to live with the fact mechs can just break on 100%+ dilation.

**Comment by chemistrymain2** [comment]
> > AFAIK the mecha "BR" missile is a bullet/projectile that only _explodes_ when it hits a sturdy target, otherwise it still does it's regular damage/AP. So I'm somewhat confident it's now a 200 damage 'gun' that holds 6 rounds.
> 
> Oh, if it's the case I'll change the damage back.
> 
> > As for the runtime, try walking forward when shooting a mech projectile gun (any non-hitscan/grenade mech gun.) There's a chance the bullet will get stuck behind the mech where it'll stay generating runtimes.
> 
> Eh, seems like a general issue with almost every gun even as human. Frok got projectiles port going, so it'll probably be fixed.
> 
> > Also.. 800 health for a Durand that can strafe is uh.. rather tough. It's tougher than the Marauder (which cannot strafe, and is also slower) which is odd because the marauder's sprite suggests it's a lot.. 'bulkier', IMHO the Durand's durability should come from it's energy shield rather then raw HP.
> 
> I guess. My idea was to make it so Duran has more health but can't really fight, whereas Marauder is basically a death sentence with less HP. I can change it around a bit.
> 
> > P.S. If you know anything about the topic limiter, could you check why mechas are causing some or all users to exceed the topic limits when using them? I'm not certain if it happens to everyone but I've seen myself and a few others have this issue, from what I've seen it's exacerbated when using slow mechs and by high time dilation.
> 
> Sorry, I can't fix time dilation. There might be a PR lying on /tg/ somewhere that solves it, but for now, we'll just have to live with the fact mechs can just break on 100%+ dilation.

Don't enable a runtime before the bug is fixed.

Keep the projectile stuff out.

Also, you've actuallly nerfed mecha weapons for their energy cannons?

**Comment by EgorDinamit** [comment]
> Keep the projectile stuff out.

Will do.

> Also, you've actuallly nerfed mecha weapons for their energy cannons?

Nerfed AP, buffed damage. I made it so it's more in line with other F13 weapons, since we're trying to phase out AP.

**Comment by githubuser4141** [comment]
If you know how to, maybe readjust some of the mecha malfunctions to be more impactful/relevant? Malfunctions like "gas tank breach" or "internal fire" are easily ignored if you don't have your mecha internals on (and why would you?), a malfunction that for example.. irradiates the pilot + surroundings, or forcibly ejects you from the mecha would be neat.. but that's probably for another PR.

OTOH, holy hell, 60 damage + 35% AP on a effectively infinite, hitscan laser rifle? I dunno if it's actually overpowered or not but I'd definitely want to not get hit by that thing.

**Comment by Weaselburg** [comment]
the heavy ap and high damage of hitscan, and effectively infinite weapons, looks like a pretty big problem to me. there's a reason the AER14 is 32 damage, .05 AP, and pretty low on ammo per cell.

**Comment by githubuser4141** [comment]
> the heavy ap and high damage of hitscan, and effectively infinite weapons, looks like a pretty big problem to me. there's a reason the AER14 is 32 damage, .05 AP, and pretty low on ammo per cell.

Yeah, a lot of people look at the armor values and go 'oh, 25% bullet resist, pffff' without realising 1. Mechs don't give a damn about AP. A 30 damage, 100 AP round won't do shit to a Durand, and 2. Mechs' armor isn't static and hitting a mech from the front increases its resistance by 1.5x. So, a Gygax will suddenly have 37% bullet, rounded to 40% (because reasons) and given it's 2.5 step_in which isn't affected by damage and it's suddenly 450 health? Wow. That's like printable gauss rifles and APA++ right there.

**Comment by EgorDinamit** [comment]
> Yeah, a lot of people look at the armor values and go 'oh, 25% bullet resist, pffff' without realising 1. Mechs don't give a damn about AP. A 30 damage, 100 AP round won't do shit to a Durand, and 2. Mechs' armor isn't static and hitting a mech from the front increases its resistance by 1.5x. So, a Gygax will suddenly have 37% bullet, rounded to 40% (because reasons) and given it's 2.5 step_in which isn't affected by damage and it's suddenly 450 health? Wow. That's like printable gauss rifles and APA++ right there.

We can always adjust the mechs and weapons as it fits.
Right now making mechs is effectively a GIGANTIC waste of materials.
Current version, in my humble opinion, is balanced, but we can always nerf it later if it turns out to be too strong as you are trying to make it out to be.

**Comment by githubuser4141** [comment]
:/ Whatever I guess, I'm hoping there's something you or Frok could do afterwards regarding the topic limiter though. Could it be nerfed as to not aggressively notify admins, disable it completely for mechs? Because I can't imagine having people spam admins with topic limiter warnings is a good feature.

**Pull request merged**
