### PR TITLE
"Outlaw" to "Raider"

### PR DESCRIPTION
**Pull request by SeeminglyTypicalUsername**
## About The Pull Request

Changes "outlaw" to "raider" to encourage more antagonistic behavior. A few slots have been added. Changed the role description to be more fitting to the role considering how lack luster it was.

New job description: 
description = "You are a member of one of the infamous raider gangs of the wastes. Pillaging, robbing, murdering wasters are a recurrent chore for your people. Depending on their affiliation, though, raiders may vary from an illiterate chemhead, to a straight edge tribal, or even a member of a group with strong connections and an unique culture based on raiding, and all of this should be considered when defining your character. Form loose connections with the rest of the underground, but be sure not to step on their toes too much."
supervisors = "your desire to make things interesting and fun. DO NOT UNDER ANY CIRCUMSTANCE play this as wastelander+."

## Why It's Good For The Game

Reverts a bad call from Desert Rose 2 which was effectively the last nail in the coffin for actual raiders. Most "outlaws" currently are just bunker looters who take the role for the loot and are either confused or too nervous to play the role like it's meant to be due to how the role is marketed. 

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
tweak: gave raiders 20 slots.
tweak: changes the role description.
tweak: changes the title of the role.
tweak: changed the supervisor text.
/:cl:

### CODE REVIEW

**Comment by gilvian** [comment]
can't wait to be again shot with half escalation since "me raider me can kill"

**Comment by panzerr1944** [comment]
> can't wait to be again shot with half escalation since "me raider me can kill"

you have jinxed it...........................

**Comment by SeeminglyTypicalUsername** [comment]
> can't wait to be again shot with half escalation since "me raider me can kill"

Those players typically aren't very robust.

**Comment by Refined1** [comment]
Based PR, undo the DR tumor.

**Comment by ogrigbe** [comment]
I don't think renaming it and adding more slots will fix the issue you've presented here. It's an idea for sure but one we need? Probably not. People will always play it as waster+ and now with more slots expect even more shit raiders who just decide to start conflict very early in, die and then just respawn again to try a second time. While I know that's an admin-ish issue I'd rather not up the slots or rename the role without it having some sort of substantial impact on the game so because of that we're going to close this for now.

**Pull request closed without merging**
