### PR TITLE
Detroit Bugfix (Now with other shit)

### PR DESCRIPTION
**Pull request by Refined1**
## About The Pull Request
Giving everyone drug recipes. In the enclave only the specialists could previously produce drugs because they spawned with the book instead of the recipe. NCR Combat Medic can also make med-x now. Every Khan loadout had a trait except one, so I gave it trekking. I also added big leagues to a vendor.

## Why It's Good For The Game
Melee is now more viable for everyone, Legion will still dominate with it due to their gigachad armor and buying the grognak book is piss expensive. 

## Pre-Merge Checklist

- [ x] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ x] You documented all of your changes.

## Changelog

:cl:
add: Med-x recipe for combat medic
add: Enclave scientist recipes
add: Big Leagues to vendor (Expensive)
add: Khan loadout with trekking

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
YEEEEAH
THE STEALTH KHAN BUFF
YEEEEEEEEEEEEAH

**Comment by Refined1** [comment]
> YEEEEAH THE STEALTH KHAN BUFF YEEEEEEEEEEEEAH

Sure, I can add a khan stealth buff

**Comment by BadAtThisGame302** [comment]
Khans need to waste MONEY for drugs....

**Comment by BadAtThisGame302** [comment]
No. You added the big leagues book for 1400 caps, that's dirt cheap.

**Comment by Refined1** [comment]
> No. You added the big leagues book for 1400 caps, that's dirt cheap.

Not as cheap as yo mama

**Comment by BadAtThisGame302** [comment]
> > No. You added the big leagues book for 1400 caps, that's dirt cheap.
> 
> Not as cheap as yo mama

😮🔫

**Comment by Refined1** [comment]
> > > No. You added the big leagues book for 1400 caps, that's dirt cheap.
> > 
> > 
> > Not as cheap as yo mama
> 
> 😮🔫

Owned, uninstall github

**Comment by Kitsunemitsu** [comment]
God can people please read the read me on the pre merge checklist area

**Comment by BadAtThisGame302** [comment]
> God can people please read the read me on the pre merge checklist area

No.  - Refined1

**Pull request merged**
