### PR TITLE
BoS map tweaks + loadout tweaks (kinda buffs)

### PR DESCRIPTION
**Pull request by ZAB909**
## About The Pull Request

Makes the bos armoury bigger, adds soda machine so bos dont die of dehydration, adds a PA repair room thats cool and tweaks BOS loadouts to actually be decent. This only buffs the loadouts that were NEVER touched, and hopefully this makes them viable and brings senior loadouts up to spec with junior loadouts. Eg, a knight would get a ripper in their close combat loadout, but the senior or head doesnt????

## Why It's Good For The Game
 I cannot test this on a local server, fyi, my stuff is a little borked but I can make PRs fine There may be a bug, who knows?
image of changes: https://imgur.com/a/FZFPyp3

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add soda dispenser to kitchen
replaced pond north of armoury with a larger armoury
removed one of those cargo pad things and put the HP office in its place
added a 'PA maintenance room' that spawns in knights and paladins
added radio and identification consoles in hp and knight office, as well as comm keys
broken (and anchored) t60 PA that the senior knight has been repairing (its just rp, no it isnt usable stfu)
add a .22 pistol and 2 mags to armoury, for under cover roleplayers (but really I want ppl to know its for placing ballistic guns/ammo there)

HP:
Added a laser pistol to the minigun loadout, just updating it to be the same as SP's loadout
SP/P:
aer9 loadout upgraded to aer12 and has power fist now. Removed laser pistol from it. Their fist is their secondary. No one uses the rifle loadout, mainly because its shit you can craft anyway. Adding powerfist and aer12 actually makes it interesting
added powerfist to all paladin 4.73 carbine loadouts. the carbine sucks dick, so this makes it better. I've tested it a few times and holy shit is it bad in comparison to the other loadouts
P:
Gave normal paladin a t45 bos instead of t51. Variety!

HK:
added ripper to shotgun loadout. normal knights get ripper but the close range one doesnt, funny. 

SK:
removed junior knight pins from close range loadout, why they got it??? idk

/:cl:

### CODE REVIEW

**Comment by zzurge** [comment]
epic

**Comment by chemistrymain2** [comment]
You also removed the pre-war ripper from senior knights.

Also no, this is a bad PR for the paladin changes. Giving EVERY SINGLE PALADIN LOADOUT A POWERFIST is a terrible idea.

**Comment by BadAtThisGame302** [comment]
Can you also remove the dense rock around the BoS base?

**Comment by SeeminglyTypicalUsername** [comment]
>adds soda machine so bos dont die of dehydration
 Bad reasoning, they can just go to the water plant.

**Pull request merged**
