### PR TITLE
Buffs and Sprites

### PR DESCRIPTION
**Pull request by Legate-Maxson**
Rigbe knows what this PR does

New Cent Loadouts

Palacents armor increased Slightly to make them an actual tank in the battle field. Starts with the weakest range weapons of all centurion loadouts the 10mm smg

Ranger Centurion lost some of its bullet resistance to give it the legions standard Melee resistance.

CQC Centurion renamed the Warlord Centurion. Now gets the updated M1919. Armor buffed by five ballistic points so its not a complete downgrade to Veteran Decanus armor

Added 14mm SMG for the vex

Added New legion axe, Identical stats to the super sledge with the axes ability to break doors and windows.

Fixed Sprite issues on some objects such as the scrap towershield and a few of the rifles in game.

Gave the Enclave Heavy Trooper loadout for the gunny back the Laser gatling to give some power back to the enclave. 
Other loadout received Hard Yard and an R91. The LSW is actually a complete downgrade to a common wasteland weapon. 

12.7 aka 14mm SMG sprite was made by Jawnner. Go tell him he's a fantastic spriter and we apprecate everything hes done for the F13 community.

### CODE REVIEW

**Comment by chemistrymain2** [comment]
This is good. Yes. Merge it. :)

**Comment by panzerr1944** [comment]
hello hi.
If the APA is getting the gatling laser now can the riot gunny get a Hard Yards book and an R91 over an LSW?
so theres a reason to pick it over the funny APA other than refusing to use the best armour and hitscan backpack gun

**Comment by Weaselburg** [comment]
the changes to cent armor would be fine if plating didn't exist. they're meant to be specialized, for the most pat, which is why you have THREE CHOICES for it

**Comment by EgorDinamit** [comment]
Document your changes properly.

**Comment by Legate-Maxson** [comment]
> the changes to cent armor would be fine if plating didn't exist. they're meant to be specialized, for the most pat, which is why you have THREE CHOICES for it.
> 
> Also, remember that the legion gets big leagues, so you're not giving veteran legionary a 60 damage weapon (THAT CAN CAUSE BLEED since it's sharp), it's a 75 damage weapon.

Seethe BOS main

**Pull request merged**
