### PR TITLE
.45-70 revolvers nerf

### PR DESCRIPTION
**Pull request by AndriyKatsubo**
## About The Pull Request

Increases the weight of .45-70 revolvers to heavy. No more shooting those one-handed.

## Why It's Good For The Game

Add realism. .45-70 is a pretty big caliber to be shot from one hand.
[https://www.quora.com/Why-does-almost-nobody-talk-about-45-70-govt-revolvers-also-known-as-BFRs](url)

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

-

### CODE REVIEW

**Comment by gilvian** [comment]
reactionayPR

**Comment by DelineFortune** [comment]
Its a pistol. Why two-handed?

**Comment by AndriyKatsubo** [comment]
> It is intended that all revolvers can be used onehanded with a shield, or they are strictly inferior to pistols OR rifles.
> 
> This is unnecessary, and realism is unimportant. Clear balance with Raptor next time.

Its damage is too high to be used with a shield, especially with current gun nerfs.

**Comment by chemistrymain2** [comment]
> > It is intended that all revolvers can be used onehanded with a shield, or they are strictly inferior to pistols OR rifles.
> > This is unnecessary, and realism is unimportant. Clear balance with Raptor next time.
> 
> Its damage is too high to be used with a shield, especially with current gun nerfs.

This is debatable, and if its damage is too high, lower its damage. Shield-revolver is an intended pairing.

Again, you can't just throw what you personally feel like doing at the wall and see if it sticks. Run these changes by Raptor first.

**Pull request closed without merging**
