### PR TITLE
Re-Adds exosuits to the RnD tree + Some minor tweaks

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request

Re-adds the marauder, durand, gygax and Clarke exosuits to the RnD tree alongside various equipment. Tested on a local server and couldn't find any glaring mistakes.

## Why It's Good For The Game

It adds extra content for tech factions and adds an 'alternative' for power armor or whatever high-end RnD items without being mass producible and therefore OP. In terms of balance the Durand/Marauder are expensive to make, can't traverse ladders and are very slow (stepin 4 and 5 respectively). In testing I found 1 1/2 magazines to the durand's side armor was enough to destroy/badly damage it.

Ports:
Ports the autocannon and shotgun SFX from [Polaris](https://github.com/PolarisSS13/Polaris/pull/8480/files).
Ports the durand shield ability from [TG](https://github.com/tgstation/tgstation/pull/45144).
Ports the Clarke & Marauder code/sprite work from [VG.](https://github.com/vgstation-coders/vgstation13/pull/16185)
Ports various balance fixes / tweaks from TGstation.

Mech tweaks:
- Gygax's speed-run function has been removed, it's step_in has been decreased to 2.5 (marginally slower than a Phazon to compensate)
- Clarke's been ruggedized so it doesn't die instantly to any hostile mob.
- Durand/Marauders have been buffed to be viable in a faction assault on a base provided you're not trying to murderbone solo. Aka, basically printable but way less flexible HTs.
- The durand's defense ability has been converted to a one-way shield. (Ported from TG!) The marauder has lost its ability to strafe so it's extremely vulnerable if there's more than one opponent. (Mechs take 2x damage from the rear.)
- Mechs can only smash through weak walls now, so they can't just stomp through 3 layers of reinforced wall.
- Simple mobs attack mechs with their actual upper/lower damages rather then their base 20 damage.
- Deflect_chance has been removed on the four added mechs, armor has been buffed to compensate.
- Power consumption has been increased across the board for mechs/mech equipment.

Other:
- Mech armor's been buffed across the board to compensate for zero deflect_chance and FO13 weaponry.
- Adds the mech LMG, shotgun, breaching missile rack, tesla/ion rifle, and three laser guns (wall-destroying pulse, heavy & standard) to RnD.
- Removes the mech clamp, mech tesla relay, wormhole generator, medical exosuits/modules and other unbalanced items.
- In SS13 mecha drills naturally work faster in vacuum or on lavaland. Buffs the mecha drills as we don't have low pressure areas.
- Mechas naturally stun their pilot when destroyed and have a high chance of causing a heavy explosion on their turf. This is to prevent people using mechs as a 2nd layer of armor for free.
- Removes deflect_chance modifiers from the mecha armor booster modules, increases the damage coeff to 0.75, increases power consumption (it's called a deflector implying it's active armor) and removes the cooldown. Buffs the repair droid to 2 health_boost and increases energy draw.

That's hopefully the entire changelog, let me know if I missed anything.

Gimmicks--
Durand's gimmick is that it's faster then the Marauder and has a shield (converts damage to battery drain instead of integrity.)
Marauder's a little stronger and has more HP compared to the Durand. Instead of a shield it has a smoke dispenser and binoculars.
The gygax is a little quicker than the Durand (2.5 step_in) and is cheaper at the cost of less HP and armour. (30 melee, 25 bullet, 40 laser)
Clarke's just a mining mech and for flavour. It's quick but can't strafe and isn't too durable.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:

tweak: Tweaks 2 simple mobs to use better projectiles. Adjusts several exosuit related things.
balance: Adds the Durand, Gygax, Clarke & Marauder exosuits to the research tree. 

/:cl:

### CODE REVIEW

**Comment by chemistrymain2** [comment]
This is a fucking awful idea, so I support it.

**Comment by Snowyypanda** [comment]
since you went and did it, make it so teh durand shield protects from all four sides

**Comment by githubuser4141** [comment]
> since you went and did it, make it so teh durand shield protects from all four sides

Sorry, not sure how to do that. It'd probably make the durand a bit OP too as positioning is pretty important in a mech.

**Comment by githubuser4141** [comment]
> This is a fucking awful idea, so I support it.

mmh. do go over it a few times incase I missed anything codewise, I'm not fantastic at this.

**Comment by chemistrymain2** [comment]
> > This is a fucking awful idea, so I support it.
> 
> mmh. do go over it a few times incase I missed anything codewise, I'm not fantastic at this.

The code seems perfectly functional. I'm just amused at the idea of a paladin in a durand and when it's broken he leaps out like a case of those russian nesting eggs.

**Comment by githubuser4141** [comment]
Buffed the post-mech explosion, now it'll heavily injure or crit you on exit. If I knew how to code better I'd make it the opposite -- if you're NOT wearing armor it should throw you clear of a delayed explosion but if you're a powergamer wearing armor whilst in a mech it'd dump you on the mech's turf instead.

**Pull request merged**
