### PR TITLE
legion wins almost every round. Time to test something real.

### PR DESCRIPTION
**Pull request by NX115**
legion balancing

## About The Pull Request

balances the legion.

## Why It's Good For The Game

Legion more unbalanced than the united states' tax spending priorities. 

## Pre-Merge Checklist

- [ x] You tested this on a local server.
- [ x] This code did not runtime during testing.
- [ x] You documented all of your changes.

## Changelog

:cl: NOXA| Yuan-SunWei| Luana|SABRIAH
fixes: the legion
balance: the legion
/:cl:

### CODE REVIEW

**Comment by NX115** [comment]
If you comment on this PR you suck cock.

**Comment by Snowyypanda** [comment]
this seems kinda hypocritical to me considering whenever i asked you for anything your go to answer was "i don't do balance prs", then again, you might have made this pr just because you got owned badly by legion and got angry, your previous comment supports my theory

**Comment by BadAtThisGame302** [comment]
How about no?

**Comment by CUST-0M** [comment]
just close this pr, for real. this is a new level of cope from NCR mains

**Comment by Gigantomidgeto** [comment]
wow so not only does this nerf every combat aspect of legion but it also attacks the loadouts of veterans and nerfs bitters
Delete your own PR this is shameful

**Comment by ZAB909** [comment]
For people who can't be bothered reading: It basically removes armour values by 30-50% for melee, bullet, laser or all for all of the legion armours. Recruit legion bullet armour literally gets cut in half, and decanus melee armour gets cut in half to equate a standard trooper's armour. What the fuck lmao.

ranger cent's laser armour is 21. Wowie. 

It also makes it so its 50% easier to OD on bitters. 

Takes away the rangemaster from explorer and gives him a fucking 45 ACP REVOLVER LMAO WHAT WHY

It gives a timer to take bitters as '15'. I don't actually know how long that is

Yeah I suck cock. Cry about it.

**Comment by Refined1** [comment]
Salt PR, time to give recruits CQC

**Comment by LocalizedDownpour** [comment]
I mean the melee armor on the legion armor is absurd. It shouldn't be at PA levels of protection 50 would be reasonable...and that's STILL pretty high tbh. You're already at a disadvantage to fight them in melee. It shouldn't be impossible however.

Don't touch Bitters. Touch grass instead they're already worse then Super Stims they don't need to be worse get real.

The Rangermaster is a good gun, it's a comically good gun. They shouldn't get the Range master...But a .45 revolver? Seriously? Just give them a fucking cowboy repeater or something, fills the same niche as the Rangemaster without being a top tier weapon.

**Comment by Weaselburg** [comment]
just give the fucking explorer a sniper rifle in place of a rangemaster, there, fair and balanced

**Comment by Sinbest** [comment]
Based.

**Comment by Legate-Maxson** [comment]
This is not being merged

**Comment by ogrigbe** [comment]
Too many negative comments and dislikes from the community

**Pull request closed without merging**
