### PR TITLE
Gank City Bunker, and mine(ore) changes for Enclave/BoS

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request
The dungeon draft remade due to issues
image
this is the draft so far

## Why It's Good For The Game
funny environmental hazards

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

:cl:
add: Added new things

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
do not nut.

**Comment by AllCorruptingWyrm** [comment]
image
Finished version is here, this is my first bunker made to be difficult, yet rewarding. I consulted Frok about it, and ensured there are the following:
Beartraps
Plasma glass turrets
mines
oil slicks
and spawners

**Comment by BadAtThisGame302** [comment]
> image
> 
> Finished version is here, this is my first bunker made to be difficult, yet rewarding. I consulted Frok about it, and ensured there are the following:
> 
> Beartraps
> 
> Plasma glass turrets
> 
> mines
> 
> oil slicks
> 
> and spawners

Can you not add so many static spawns? That's quite cringe.

**Comment by AllCorruptingWyrm** [comment]
furthermore:
PR renamed to account for a couple changes regarding loot outside the Enclave base (in turn, they get mutfruit, xander, broc, etc) and a t4 spawner after closing their t5s outside of base
some more ore was added by the bos to compensate with the expanded bunker
other than that, this is it.

**Comment by AllCorruptingWyrm** [comment]
> 

sure I guess, I mostly copied from other places.

**Comment by AllCorruptingWyrm** [comment]
image
adjustments done as asked, this is essentially it and with that I remove DNM and work on something else, unless I forgot something.

**Pull request closed without merging**
