### PR TITLE
Lower total train time to 7 minutes

### PR DESCRIPTION
**Pull request by XElectricX**
## About The Pull Request

Yuma's new hyper sonic train. Take 2 minutes to arrive, waits for 5 minutes at the station, transfer time to EORD arena takes 10 seconds.

## Why It's Good For The Game

It took about 25 minutes in total for the train to do it's thing. The arrival time takes 2 minutes to serve as a notice, and will wait for 5 minutes at the station. People have time to board now instead of kicking rocks waiting for it to arrive. The departure transfer time takes 10 seconds because it served no purpose other than filler.

## Pre-Merge Checklist

- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog

:cl:
tweak: Train arrival takes 2 minutes, waits for 5 minutes, departure takes 10 seconds
/:cl:

### CODE REVIEW

**Comment by chemistrymain2** [comment]
nah keep the departure transfer time the same train EORG is funny

**Comment by gilvian** [comment]
Leave it as it is. With train coming people at least have a reason to go somewhere and finish up raids and roleplay, with 7 minute train you can't really finish a raid and all the factions will be stuck fighting without being put on a train.

**Comment by DelineFortune** [comment]
Why cant we have vote for long-short trains

**Comment by BadAtThisGame302** [comment]
I think it's fine as is.

**Comment by Serxule** [comment]
"lets make it so if you want to go to the train you literally have to drop everything and run"

no thats not a good idea

**Pull request closed without merging**
