### PR TITLE
fix Book of ancient knowledge not giving "Desert Affinity" choice

### PR DESCRIPTION
**Pull request by TheLeopold**
## About The Pull Request
Single line fix, I did not test it.

## Changelog

:cl:
fix: tribal's book of ancient knowledge now gives choice for Desert Affinity
/:cl:

### CODE REVIEW

**Comment by gilvian** [comment]
Desert Affinity is Wasteland survival guide, meaning you get less slowdown from the environment (I think)

Trilabs spawn with it

**Comment by Legate-Maxson** [comment]
Tribal's start with desert affinity this PR is retarded

**Comment by TheLeopold** [comment]
Interesting thing as tribal's book has
`994			if("Desert Affinity")
995				granted_trait = TRAIT_HARD_YARDS
996				traitname = "trekking"`
Why would it be there?

**Comment by gilvian** [comment]
no clue, tribals already start wiht trekking anyway so ??????

**Pull request closed without merging**
