### PR TITLE
Legion Time

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Everything should be in the changelog

## Why It's Good For The Game

The Venator being a direct copy+paste of the NCR Vet Ranger is annoying, so I made him a melee guy to have at least SOME difference from the Vet Ranger. MP5's are pretty busted to be given round start so they're gone, instead Spec's get Uzi (Probably a direct downgrade of the MP5) and Explorers get a ballistic fist, moving toward more melee loadouts and stuff since Legion almost have no melee only loadouts and they're meant to use melee at least a bit more than the average waster. Grenade launcher duel wielding bad. Two Legion NVGs while NCR get one bad. 

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Gives Enclave Specs an Uzi
add: Gives Legion Explorers a ballistic fist
add: Gives the Venator a super sledge.
del: Removed the MP5's from Enclave Specs and Legion Explorers
del: Removes the venators sniper rifle
del: Removes the Venator's NVGs
balance: rebalanced the grenade launchers to stop people from duel wielding them
tweak: tweaked the Orator to have a .357 revolver
fix: fixed the Legion loadout descriptions
/:cl:

### CODE REVIEW

**Comment by Suxleftnux** [comment]
why not simply make it two different loadouts

**Comment by BadAtThisGame302** [comment]
> why not simply make it two different loadouts

Done

**Comment by Legate-Maxson** [comment]
Right so this PR is a balancing Nightmare. The UZI does the same damage as the MP5, But has a GREATER rate of fire then the MP5. The MP5 is just more accurate which is undone by a recoil comp to make them both bullet lasers. The ballistic fist should never be a loadout because if loaded with trainshot it would do 80 damage at .2 pen with knockback which would pretty much a one shot anyone at this point. 

The launcher not being duel wieldable shouldn't be a thing so I'm fine with that.

but holy shit honestly quite incredible

**Comment by chemistrymain2** [comment]
> Right so this PR is a balancing Nightmare. The UZI does the same damage as the MP5, But has a GREATER rate of fire then the MP5. The MP5 is just more accurate which is undone by a recoil comp to make them both bullet lasers. The ballistic fist should never be a loadout because if loaded with trainshot it would do 80 damage at .2 pen with knockback which would pretty much a one shot anyone at this point.
> 
> The launcher not being duel wieldable shouldn't be a thing so I'm fine with that.
> 
> but holy shit honestly quite incredible

uzi rof:

	autofire_shot_delay = 2
	
mp5 rof

	autofire_shot_delay = 2
	

i have no idea what your'e on about raptor the uzi has the same rof as the mp5sd on autofire 

also the ballistic fist cannot melee at the same time that it fires, so it would not do 80 damage. pointblanking was removed.

what actually happens is that since trainshot fires 3 pellets of 15 damage 15 stamina .4 pen, that would be 45 brute (before armor reduction) 45 stamina (before armor reduction) with an 8% chance per pellet to throw the target (so, a total 22% chance for at least one of the pellets to throw the target, and throws no longer knockdown the target in question)

since the ballistic fist has a fire delay of 4.5 that's 4.5 deciseconds before they can fire the second shell in there.

while basically loading it with trainshot DOES make it really powerful, it's actually not all that much different to sawing off a widowmaker shotgun and loading it with trainshot, except that it CAN double as a melee weapon if you wanted

**Pull request closed without merging**
