### PR TITLE
Makes Cleaner Grenades bigger, but no slip

### PR DESCRIPTION
**Pull request by CocaColaTastesGood**
## About The Pull Request
Makes Cleaner Grenades bigger, but no slip

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
fix: Makes Cleaner Grenades bigger, but no slip
/:cl:

### CODE REVIEW

**Comment by CocaColaTastesGood** [comment]
Makes Cleaner Grenades bigger, but no slip

**Comment by SeeminglyTypicalUsername** [comment]
bad

**Comment by chemistrymain2** [comment]
This makes all foam not slippery.

Do not merge.

**Comment by CocaColaTastesGood** [comment]
> This makes all foam not slippery.
> 
> Do not merge.

I'm aware, why should foam be slippery by default though?

**Comment by BadAtThisGame302** [comment]
> > This makes all foam not slippery.
> 
> > 
> 
> > Do not merge.
> 
> 
> 
> I'm aware, why should foam be slippery by default though? This is also the only foam grenade that isn't makeable in chemistry. I'll make a cleaning foam subtype if you prefer that.

All foam should be slippery because the Enclave want to slip people in their hellfoam 😃

**Comment by gilvian** [comment]
i say we add to the cleaner granades a bit of pax chem just to make cleaning easier and more peaceful

**Comment by CocaColaTastesGood** [comment]
I'll be making a cleaning foam subtype and using that instead.

**Pull request closed without merging**
