### PR TITLE
wateland doctor QoL

### PR DESCRIPTION
**Pull request by NX115**
allows the wasteland doctor to actually do doctor shit as to not make them entirely reliant on shit that can be stolen during the round.

## About The Pull Request

This allows wasteland doctors to be closer to a Followers Doctor in terms of what they can do, allowing players to play a doctor without having them essentially be forced to take followers — something I've been informed can happen quite a lot since it seems like they don't have that many slots. 

## Why It's Good For The Game

This adds a few items and traits to the wasteland doctor's loadout, allowing them to basically not have to rely on no one stealing medical supplies.

## Pre-Merge Checklist

- [x ] You tested this on a local server.
- [x ] This code did not runtime during testing.
- [x ] You documented all of your changes.

## Changelog

:cl: NOXA| Yuan-SunWei| Luana|SABRIAH
balance: giving wasteland doctors the means to actually do doctor shit
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
This is a nice way for everyone to literally now always pick Wasteland Doctor for the chem and surgery knowledge.

**Review by EgorDinamit — CHANGES_REQUESTED** [review]
Properly document your changes. All of them.
As much as I'd like to see wastie doctors have any use, giving them FOUR traits is too much. I'd say go for low surgery skills and that's it.

**Comment by NX115** [comment]
> This is a nice way for everyone to literally now always pick Wasteland Doctor for the chem and surgery knowledge.

Picking a class for just the boosts and not the intention to play? HMMMMMMMMMMMMMMMMMMMMMmmmmmmm.
Sounds like powergaming might be a problem.

**Comment by ogrigbe** [comment]
Agreed, too strong

**Pull request closed without merging**
