### PR TITLE
Re-adds fortnite building and see-through floors

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

See above.

In this PR, I have reenabled see-though floors, and you can now build without supports again.

## Why It's Good For The Game

LET 👏 PEOPLE 👏 ENJOY 👏 THINGS 👏

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Legate-Maxson** [comment]
No glass floors, and if you want a little more leniency on the building increase the amount of platforms that can be made without an anchor. Fortnite building was added originally with the intent to make the server worse so it will not be seen making a come back.

**Comment by xTrainx** [comment]
Based

**Comment by chemistrymain2** [comment]
Eh i'll readd glass floors, fortnite building needs a conditional. Make a subtype of rods out of plasteel and use those as lattice construction for unsupported.

**Comment by Erdrom** [comment]
let the people have fun

**Comment by Cartlord** [comment]
For the unaware, I'll explain: glass floors were used to spy on people through Z-levels - I saw one group go to the area of Yuma that's directly above the Brotherhood of Steel bunker and lay down glass floors to watch them.

**Comment by BadAtThisGame302** [comment]
image

**Comment by Legate-Maxson** [comment]
Yet to make any changes so this will be closed.

**Pull request closed without merging**
