### PR TITLE
Changes AER14, AER12 and Wattz2k damage and wound bonus.

### PR DESCRIPTION
**Pull request by Erdrom**
## About The Pull Request

Changes AER14, AER12 and Wattz2k damage and wound bonus. Nerfs slightly AER14 and AER12. Changes the wound bonus of the Wattz2k as a sniper laser weapon.

## Why It's Good For The Game

We seem to forget laser weaponry is hitscan meaning that the silly damage of the AER14 and AER12 are unjustified in practice. As someone who actually plays the game I find this change a small bandaid for the incredibly good hitscan strat. Also improves Wattz2k wound bonus due to the fact that is a good sniper weapon that is often underused and I'm even considering improving it's damage, however I think it's already quite good.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by OliOliOnsiPree** [comment]
-1. Weapon balance is already in the works, youll never see these weapons afterwards.

**Comment by ZAB909** [comment]
Wtf my funny laser -1.

**Comment by Erdrom** [comment]
> -1. Weapon balance is already in the works, youll never see these weapons afterwards , Outlaws can be increased thats fine jsut not the weaponry balance.

Well might as well close this one then

**Comment by Legate-Maxson** [comment]
Weapon rebalance is tonight so this PR is moot.

**Pull request closed without merging**
