### PR TITLE
Respawn timer set to 20 minutes

### PR DESCRIPTION
**Pull request by Hadoje**
## About The Pull Request
Sets the respawn timer to exactly 18000 deciseconds, or in sane time measurements: 30 minutes
Have mercy on me, this is my first PR.

## Why It's Good For The Game
As funny as it is to dunk on a ranger with a warhoned axe, it's not fun for anyone else.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: Set respawn timer to 12000 (Was going to be 18000 originally)
/:cl:

### CODE REVIEW

**Comment by xTrainx** [comment]
What?

**Comment by AndriyKatsubo** [comment]
Got killed by the respawned player and now made a PR, huh?

**Comment by gilvian** [comment]
i mean I agree respawn timer of 5 minutes is dumb but 30 is too much, maybe 15 would be good?

**Comment by BobNewman-max** [comment]
lets gooo 30 minute respawn timers what could go wrong right? 

I like the idea that players have to value their lives a bit more but be careful with pushing that idea too hard, they might value their lives TOO much and it'll turn into either TG style round-times or it'll just straight become lifeless with no-one fighting anyone unless they know they can 100% win.

**Comment by Hadoje** [comment]
> i mean I agree respawn timer of 5 minutes is dumb but 30 is too much, maybe 15 would be good?

The reason It's 30 is because of the 10 minute esc rule being weird and uncertain at times, especially with factions skirmishing all over the map at times after a raid is done, also gives time for people to get their shit together and/or maybe find something else to do without having to worry about Recruitus Moggius running in.





> lets gooo 30 minute respawn timers what could go wrong right?
> 
> I like the idea that players have to value their lives a bit more but be careful with pushing that idea too hard, they might value their lives TOO much and it'll turn into either TG style round-times or it'll just straight become lifeless with no-one fighting anyone unless they know they can 100% win.

From my experience from other servers, people still go around and fight. A 30 minute respawn timer doesn't stop you from trying to mog others. Rounds last up to a total of 3 hours at least, so unless you're getting killed every time you respawn IT SHOULD be fine. However, I'll keep that in mind if people find it too much. Right now, I'm just focused on making sure I somehow didn't break everything by changing a single timer.

**Comment by Hadoje** [comment]
Changing the timer to 20 minutes

**Comment by SeeminglyTypicalUsername** [comment]
Thanks for the horrible PR

**Comment by Starfirejordan** [comment]
what is this shit

**Comment by SeeminglyTypicalUsername** [comment]
> Changing the timer to 20 minutes (I'm too dumb to be able to change my own commit)

How about you don't change it at all?

**Pull request merged**
