### PR TITLE
Tribal Centurion + 4 NCR Medic Loadouts

### PR DESCRIPTION
**Pull request by ZAB909**
## About The Pull Request
Adds a melee only Berserker Tribal Centurion. With a fuckton of throwing weapons. Adds 4 NCR Medic loadouts.

## Why It's Good For The Game
Variety, cent loadout is a little roleplay-y but it isn't crap. 
Removed 2 armour plates from medic default.
NCR Medic loadouts are:
Backline: Medhud, 2 supers, semi 9mm pistol, advanced health scanner and ancient (followers) first aid kit
Trooper: service rifle, 1 super, m1911, decent meds.
Ranger supporter: Funny ranger gask mask and knife, dual .357 revolvers. 2 additional plates. Has the least medical
Vanguard: Foldable M1. m1911. Ancient (followers) first aid kit. 

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:

/:cl:

### CODE REVIEW

**Comment by Legate-Maxson** [comment]
No

**Comment by BadAtThisGame302** [comment]
No

**Comment by panzerr1944** [comment]
No

**Comment by ogrigbe** [comment]
raptor said no so i agree with him because most of the time he knows whats going on sometimes.

**Pull request closed without merging**
