### PR TITLE
Makes mutation toxins unsynthable

### PR DESCRIPTION
**Pull request by CocaColaTastesGood**
## About The Pull Request
Using them in game makes admins mad, no point in making it possible to get them.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
fix:  mutation toxins unsynthable
/:cl:

### CODE REVIEW

**Comment by SeeminglyTypicalUsername** [comment]
Don't merge this

**Comment by CocaColaTastesGood** [comment]
> Don't merge this

then don't complain about me being a powergamer golem

**Comment by AllCorruptingWyrm** [comment]
no one ever complained

**Comment by Serxule** [comment]
no one ever mentioned anything about these, and they're funny

**Comment by biotear** [comment]
> ## About The Pull Request
> Using them in game makes admins mad, no point in making it possible to get them.
> 
> ## Why It's Good For The Game
> ## Pre-Merge Checklist
> * [x]  You tested this on a local server.
> * [x]  This code did not runtime during testing.
> * [x]  You documented all of your changes.
> 
> ## Changelog
> 🆑 fix: mutation toxins unsynthable /🆑

Consider, no. Nobody wants this and if anyone tells you otherwise, nobody who matters.

**Comment by zzurge** [comment]
yeah nah bruh

**Comment by AllCorruptingWyrm** [comment]
i'm going to revert this immediately if this gets merged

**Comment by Refined1** [comment]
Good PR, keep it up!

**Comment by BobNewman-max** [comment]
based

**Pull request merged**
