### PR TITLE
Tweaks to Enclave loadouts + fix plasma pistol damage output

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

- Renames "Gunnery Sergeant" to "Master Sergeant". Changes their fluff text.
- Slightly changes loadouts of the Lieutenant and Master Sergeant: Laser loadout of LT now has plasma pistol instead of shoddy disabler; MSGT has APA on by default, loadouts only decide what weapons he gets.
- Added loadouts to SGTs - ballistics with their usual stuff, and AER9 one.
- Fixes plasma pistol damage, as the "worn" pistol was, in fact, dealing twice as much damage as "normal" one.

## Why It's Good For The Game

- Ain't navy here and nobody even knows what "Gunnery Sergeant" is supposed to be. Everyone played it as "role below LT, but above SGT" and I don't see any issues with it.
- LT having disabler made no sense, at all. As for the MSGT, everyone picked laser loadout simply for the APA, because riot armor SUCKS.
- Allows Sergeants to have some choice of their weaponry.
- "Normal" plasma pistol dealt 16 damage, "worn" plasma pistol dealt 32. Makes no sense? Exactly.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by LocalizedDownpour** [comment]
Just fucking readd Heavy Infantry already. Give it two slots, and remove the Sergeant role to compensate. Take the APA from the Gunnery/Master Sergeant and give him his cool riot armor.

Sergeant Role is virtually never used. It's only loadout is dog water.

**Comment by LocalizedDownpour** [comment]
> > Just fucking readd Heavy Infantry already. Give it two slots, and remove the Sergeant role to compensate. Take the APA from the Gunnery/Master Sergeant and give him his cool riot armor.
> > Sergeant Role is virtually never used. It's only loadout is dog water.
> 
> Or just give the SGT's the APA and not change the name to Heavy Infantry

Also fine.

**Comment by panzerr1944** [comment]
keep gunny riot. its cool.

**Comment by CaputCapital** [comment]
> Just fucking readd Heavy Infantry already. Give it two slots, and remove the Sergeant role to compensate. Take the APA from the Gunnery/Master Sergeant and give him his cool riot armor.
> 
> Sergeant Role is virtually never used. It's only loadout is dog water.

Sergeant Role is actually used.

**Comment by EgorDinamit** [comment]
> Sergeant Role is actually used and I know it could use attention in the form of two different loadouts at least.

That's what I did. It could certainly use some more work, but there is now a pretty simple choice between r91 and AER9.

**Comment by ZAB909** [comment]
I think all the changes are good, it doesn't matter if heavy trooper is added back imo, because enclave still needs NCO roles and if they get added back, just make the SGTs them. I'd say giving the old marine loadout armour to LT in the future is always a possibility to people who really liked the kit.

**Pull request merged**
