### PR TITLE
Revert "Snips enclave slots by 3"

### PR DESCRIPTION
**Pull request by chemistrymain2**
People play BoS now.

No longer a reason to cut it.

### CODE REVIEW

**Comment by ZAB909** [comment]
1+

**Comment by BadAtThisGame302** [comment]
-1

**Comment by Serxule** [comment]
probably want to uhhh not do this 
Screenshot_2399

**Comment by ZAB909** [comment]
People are now playing bos. I think a good change would be 1+ Pvt and 1+ spec at least. Maybe 2 pvts is too much

**Pull request merged**
