### PR TITLE
enclave base underground made cool/..,?

### PR DESCRIPTION
**Pull request by panzerr1944**
holy shit.
the base isnt tiny now??
its.. not near the invincible walls of the edge of the map,.,.
its., big.,.,/.,/?
.,purpl.,.,thang.,.//??
image
Makes the enclave base bigger, more accessible and generally more fun to use than the tiny shit it used to be. 100% confirmed cool PR as it includes an orion trail machine and he-who-dwells-within-your-walls (He is in your walls)(he is a pile of bones)((also not included in the picture due to it being a recent edit is an extra wall layer on the armoury so it wont get insta-killed every raid))(((hello 3rd update here i include new picture now yes, i forgor a sign for hydro so i put in)))

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Hahaha, you need approval for first time contributions, what a nerd!! 😆

**Comment by panzerr1944** [comment]
> Hahaha, you need approval for first time contributions, what a nerd!! 😆

https://user-images.githubusercontent.com/76122712/165871290-c1b42956-d038-43df-8e5c-bfba50076e4a.mp4


perish

**Comment by Sinbest** [comment]
uhhh, based alert??

**Comment by panzerr1944** [comment]
> He is in our walls get him out get him out looks awesome and is a vast improvement over mine
> 
> Only complaints is that I think very big hallways with no doors in it is cringe and sucks for defence. But 3 wide hallways shouldnt be doored either so idk.

bigger hallways means more space. you can make your own big defenses and chokepoint airlocks with multilayer plasteel walling. the space is there, you just gotta do it

**Comment by 5467543** [comment]
pruple thing

**Comment by ogrigbe** [comment]
I hate the enclave, I hate the enclave, I hate the enclave

**Comment by panzerr1944** [comment]
> I hate the enclave, I hate the enclave, I hate the enclave

i agre

https://user-images.githubusercontent.com/76122712/166065435-443f9e77-e161-447d-b759-01d30001f08b.mp4

**Comment by panzerr1944** [comment]
redoing the pr because people keep updating underground.dmm and it means merging this wont work. pure agony

**Pull request closed without merging**
