### PR TITLE
Revert "Respawn timer set to 20 minutes"

### PR DESCRIPTION
**Pull request by chemistrymain2**
Reverts fortune13-ss13/thewasteland#765

Everyone hated this and the server pop is too low.

### CODE REVIEW

**Comment by SeeminglyTypicalUsername** [comment]
do not merge this ( for dubious reasons :) )

**Comment by Hadoje** [comment]
**John Smith** (Recruit Legionnaire) has arrived at **Legion Camp**

**Johannus NCR** (NCR Conscript) has arrived at **Camp Miller**

**Comment by Wotzizname** [comment]
Removing the 30 minute timer won't make any of the pop come back and if you die, you should just get better at thr game.

**Comment by SeeminglyTypicalUsername** [comment]
> Removing the 30 minute timer won't make any of the pop come back and if you die, you should just get better at thr game.

yes it  would lmao, that's why you shouldn't merge it

**Pull request closed without merging**
