### PR TITLE
Removal of non-essential hard rocks.

### PR DESCRIPTION
**Pull request by KillerGryphon**
## About The Pull Request

As requested by Frok, to remove barriers to playing and strategy and so forth, I have removed most indestructible rock on the surface and underground. This includes anything NOT a bunker or dungeon, so all faction bases that were once protected by said indestructible rock, no longer have that protection, while the dungeons and such are still protected so you have to work for that sweet loot.

## Why It's Good For The Game

Opens up the playing field for strategy and allowing new directions to raiding and expansion.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by githubuser4141** [comment]
Doesn't this mean people can inadvertently drill into faction bases as a result from mining or accident to be valid-killed by the faction members or banned by an admin?

**Comment by KillerGryphon** [comment]
> Doesn't this mean people can inadvertently drill into faction bases as a result from mining or accident to be valid-killed by the faction members or banned by an admin?

A good question! It likely won't be a common occurrence outside of new players, but a random waster who sticks around after drilling into a base isn't going to long for this world, you're right. Banning them though? Unless they're raiding, which is already defined in the rules, it's just breaking into somewhere, and should be handled appropriately, I'm not concerned about that.

**Comment by BadAtThisGame302** [comment]
> > 
> 
> The actual admin/s in-game say that B&E into a faction base without admin permission is indeed a unauthorized faction raid and you can be banned for it. It's not just new players either, it's fairly difficult to gauge exactly where you are without mesons or x-ray vision and even then it's tricky if there's material deposits nearby. Maybe add breakable walls so players don't accidentally breach bases with their mining cutters.

Have you ever seen anyone mine on the surface? Plus why are you mining close to the NCR/Legion base in the first place?

**Comment by Weaselburg** [comment]
does this remove the indestructible rocks covering the 'first floor' of the BoS bunker? given that it's supposed to be it's own level having it be able to mine into might not make sense. Or it could make raids more fun, I don't really know either way.

**Pull request merged**
