### PR TITLE
Re-adds some weaponised circuits back (Since Panzer is doing my slowdown change on his PR I am using this PR for the re-introduction of weaponised circuits)

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

The grenade, cannon and stun primer didn't seem that harmless, so I added them back and kept the weaponised circuits removed because a lot of people (The two guys that powergame circuits in the first place) asked for them back, so why not.

## Why It's Good For The Game

Minor balance issue

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added some of the weaponised circuits backed
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
40-60-40 is weaker than vet armor

**Comment by BadAtThisGame302** [comment]
> 40-60-40 is weaker than vet armor

If you ever complain about any code and not check it I will literally skull fuck you, shut up.
image

**Comment by Serxule** [comment]
> > 40-60-40 is weaker than vet armor
> 
> If you ever complain about any code and not check it I will literally skull fuck you, shut up. image

thats their unplated armor nerd

**Comment by BadAtThisGame302** [comment]
> > > 40-60-40 is weaker than vet armor
> > 
> > 
> > If you ever complain about any code and not check it I will literally skull fuck you, shut up. image
> 
> thats their unplated armor nerd

And?

**Pull request merged**
