### PR TITLE
More BOS tweaks

### PR DESCRIPTION
**Pull request by ZAB909**
## About The Pull Request
Removes dense rock near elevator. Degrades powerfists in ranged paladin loadouts to ripper. Gives SK their pre war ripper back.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
removed some weights and moved recycler
/:cl:

### CODE REVIEW

**Comment by KillerGryphon** [comment]
Hmmm. I'm for this, but I also feel like maybe there should be a choice of JUST a power fist?

**Comment by ZAB909** [comment]
If you want a power fist, you go the melee paladin. Which has power fist, aer7 and a super sledge

**Comment by ZAB909** [comment]
(reminder that HP starts with a power fist at all times as well)

**Comment by KillerGryphon** [comment]
> If you want a power fist, you go the melee paladin. Which has power fist, aer7 and a super sledge

Whoops I missed that in the loadouts. Carry on then!

**Pull request merged**
