### PR TITLE
Establishing 'Climax' verb

### PR DESCRIPTION
**Pull request by NX115**
## About The Pull Request

This pull request brings in the ability to climax, essentially bringing
back function to genitals. Because, as of now, people need the
'masochist' trait to cum via slapping themselves. 

Lewd chems have also been added to give players control over
their genitalia. 

## Why It's Good For The Game

Returning functionality that should've never been removed, especially
when there are already plenty of examples of sexual fluids strewn across
the map.

Lewd chems have also been added to give players control over
their genitalia. 

## Pre-Merge Checklist

- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog

:cl: NOXA| Yuan-SunWei| Luana|SABRIAH
add: 'climax' verb
add:  lewd chems
/:cl:

### CODE REVIEW

**Comment by TheRealScarHomie** [comment]
https://i.gyazo.com/7dfbf61804d2c665967ebd5c201429be.gif

**Comment by chemistrymain2** [comment]
Depressingly, this actually would probably reduce genital lag since it optimizes the code a little.

I think we may actually have to merge it.

**Comment by BadAtThisGame302** [comment]
😭🔫

**Comment by Legate-Maxson** [comment]
I hate it, but it fixes so many runtimes....

**Comment by NX115** [comment]
> Depressingly, this actually would probably reduce genital lag since it optimizes the code a little.
> 
> I think we may actually have to merge it.




> I hate it, but it fixes so many runtimes....



> 😭🔫




[**When your horny code happens to fix runtimes**](https://youtu.be/ztzq05IzYds)

**Pull request merged**
