### PR TITLE
Ghouls not healing from chems

### PR DESCRIPTION
**Pull request by Refined1**
## About The Pull Request
For too long have the ghouls been recieving HUMAN tier healing, fuck em'.

## Why It's Good For The Game
Ghouls already have passive healing, they don't require chem healing to stop ontop of it. Plus it was broken so if the ghouls ran the tribal trait they didn't even get the healing debuff meaning that they will heal the same amount as your average retard ontop of the passive radiation healing.

## Pre-Merge Checklist

- [x ] You tested this on a local server.
- [x ] This code did not runtime during testing.
- [x ] You documented all of your changes.

## Changelog

:cl:
Ghouls don't heal from powder etc.
/:cl:

### CODE REVIEW

**Comment by ZAB909** [comment]
Ok so... change the tribal trait? Make it so ghouls don't get as much as stims as others? I read a PR that did that, I assumed it was merged but idk. Ghouls just not having any stims at all doesn't sound like fun gameplay at all.

**Comment by 5467543** [comment]
fuck them kids

**Comment by chemistrymain2** [comment]
Not having any healing was tested and won't work

Disable the tribal trait for them, they weren't meant to have it

**Comment by Refined1** [comment]
Closing this PR because Adam wanted to do his own solution to nerfing Ghouls. You've done this to yourself, Ghoultards.

**Pull request closed without merging**
