### PR TITLE
Update Pahrump-Surface-2.dmm

### PR DESCRIPTION
**Pull request by ogrigbe**
Removes some of the lame houses south of the NCR. 

Creates a shrine to a fallen friend.

Adds a small fishing spot for nature purposes.

Removes dogs from the small salvaging yard. Nobody so far has welded any of those cars so they just sit there and do nothing all round.

Shrunk mirelurk cave for more open desert, hoping that if anything it can be a better area to skirmish between factions and if someone wants they can put something new there. Time to revamp some of the older buildings to make the wasteland more unique. More flora would be appreciated

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Did you update the roofs/caves above of what you're removing? With only the surface changed I presume not.

**Comment by ogrigbe** [comment]
I did not, I also moved the small jungle bunker ladder into the building to its left.

**Comment by ogrigbe** [comment]
Thanks for the reminder I'll hop in and do the roofs now

**Comment by Cartlord** [comment]
The junkyard mobs really need retooled, because the radroaches can't leave a very small area.

**Pull request merged**
