### PR TITLE
Followers Remap

### PR DESCRIPTION
**Pull request by Kitsunemitsu**
## About The Pull Request
This remaps the followers to be a little more user friendly

Previews:
Kitchen & Botany moved upstairs
image
image

And there a triage room has been added separate from the surgery room
image

## Why It's Good For The Game
This is done by request of a followers player, who has said the following:

"FoA are constantly with their slots full. 
Specially on their doctors. 
It doesn't fit the current population the server has been getting so with more slots we've also fixed the tight feel of the small followers clinic.
Plus, if any of the roles ever die, that's a permanent drawback on the slots either by a 1/3 or 1/2"

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: increased the size of the follower's base, and moved some things around.
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
The slot changes seem drastic, the mapping changes seem fine, I do not think we should give the Followers more slots, especially more Doctors.

**Comment by Refined1** [comment]
Remove followers and add Kebab

**Comment by BadAtThisGame302** [comment]
> Remove followers and add Kebab

Okay

**Comment by Legate-Maxson** [comment]
Map is fine. Your slots are not. Remove them and this can be merged.

**Comment by Kitsunemitsu** [comment]
Gotcha, will do

**Comment by cornercube** [comment]
try to reduce the underground area a bit, instead of just adding to the second floor, so that the total size doesnt increase so drastically

you can also reduce the balcony area a bit and squish it down a little, since its mostly empty space

**Comment by 5467543** [comment]
>tfw followers erp on duty so much we're considering adding more slots just so they can do their job

**Pull request merged**
