### PR TITLE
Return of the GodFather

### PR DESCRIPTION
**Pull request by AllCorruptingWyrm**
## About The Pull Request

This is a PR to add back the Den.

## Why It's Good For The Game

Gives Khans someone to fight, adds another neutral-evil faction to contest with other factions, more variety.

## Pre-Merge Checklist

- [X] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog

:cl:
add: adds den to a degree.
/:cl:

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
image
This is going to be the map as well.

**Comment by AllCorruptingWyrm** [comment]
image
Requesting feedback.
This is it so far, I'll be letting this sit for a day or two to get feedback before I test it and remove the PRs "draft" status.
Please watch mapping PRs,

**Comment by AllCorruptingWyrm** [comment]
image
This is basically the map as it stands.

**Comment by AllCorruptingWyrm** [comment]
with that final commit today, I'm proud to announce this PR is ready for review.
Note I MIGHT have bungled something super hard but its going to be a subtle thing if anything, but I've checked the map over a number of times.
This is also the first time PR I have made of this caliber so forgive any mistakes but we should be fine.

image
This is the map as it stands.

**Comment by AllCorruptingWyrm** [comment]
also, thank you to @Kitsunemitsu for helping me sort out the coding itself.

**Comment by Sinbest** [comment]
Gates please, this is comically easier to invade than the older then

**Comment by AllCorruptingWyrm** [comment]
added.

**Comment by AllCorruptingWyrm** [comment]
we should be done, loaded it up local and all that and, I don't see any issues however I might have forgotten a light or two but I just fixed it.

**Pull request merged**
