### PR TITLE
Deletes Colormates + Fixes raidertown CS source

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Fixes this and removes the public colormates, seeing people use them to be way too bright or dark colors is cringe, along with Vet Ranger armor sprayers (Legion) no more!
image

## Why It's Good For The Game

Bug fixes good, also the bright colors from the colormate make me sick, along with Legion spray painting Vet Ranger gear 30 minutes in the round red (Fuck you)

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added pockets to the Vet Ranger armor (Making it sprayable using a brain)
del: Removed the two colormates on the map
tweak: tweaked the raider CS source incident
/:cl:

### CODE REVIEW

**Comment by OliOliOnsiPree** [comment]
Thank god, the public colormates are removed 🙏

**Comment by Zebraman** [comment]
Nooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by BadAtThisGame302** [comment]
> Nooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Get a load of this guy.

**Comment by CaputCapital** [comment]
Fixed raidertown CS source? I agree.

Removing the colormate, from both Oasis and Den?
.
.
.
.
.
.
.
You thought I was going to say "FUCK YOU BADATTHISGAME302 YOU PIECE OF SHIT-CODING PRICK!!!" didn't you?
But I have a better idea now that the colormate is gone, hahaha.

**Pull request merged**
