### PR TITLE
Tribal chemistry + implementation, minor balancing

### PR DESCRIPTION
**Pull request by CUST-0M**
## About The Pull Request

Adds in a reskinned chem dispenser and chem heater for tribal/legion use, implements it for the legion alongside crafting recipes to convert the originals and a crafting recipe to turn the plant DNA manipulator and DNA disks into a reskinned tribal version. Removes the HT minigun and Veteran Ranger dual colts since the NCR no longer needs a crutch. Balances out Legion non-combatant roles since there's only 1 forge (so 1 forgemaster) and more Auxilia in its place. Vets get iron fist cuz why not.

## Why It's Good For The Game

The Legion can get on that warcrime grindset like literally every single other faction with the chemistry and plant DNA stuff (they still need to get the board and disks like everyone else). Auxilia is often criticized for being the boring bitter farm role so giving them a chemistry setup should change that. The increase in skilled NCR players means they don't need to have two overly-powerful loadouts to fight the Legion anymore.

Is the Legion having chemistry 100% lore accurate? No. Is it fun? Yeah.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Primitive chem dispenser
add: Primitive chem heater
add: Primitive plant DNA machine
add: Primitive plant DNA disks
tweak: Legion non-combatant roles
tweak: Prime spawns with trekking instead of having to read the book
balance: Veteran iron fist
balance: HT minigun replaced by heavy service rifle
balance: Veteran Ranger long colts loadout removed
/:cl:

### CODE REVIEW

**Comment by ogrigbe** [comment]
Fix the conflicts and I will add it

**Comment by BadAtThisGame302** [comment]
So what's with the NCR nerfs in a chemistry PR? U mad??

**Comment by CUST-0M** [comment]
the ncr players got better they don't need the minigun and colts anymore

**Comment by ScratKnapp** [comment]
a PR for tribal chemistry shouldn't have a completely unrelated ncr nerf stuck in

**Comment by AllCorruptingWyrm** [comment]
the players didnt get better we literally got rolf o stomped in a raid this morning you dingus

**Comment by CUST-0M** [comment]
new one up

**Pull request closed without merging**
