### PR TITLE
Minigun overheat is back

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

When the HT sprays down the road with his 300 round minigun 
image

## Why It's Good For The Game

Because... based?

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added minigun overheat back
/:cl:

### CODE REVIEW

**Comment by ZAB909** [comment]
You dont get it he saw a legion explorer there he had to. The 3 wasters he killed were worth it. 1+

**Comment by Serxule** [comment]
30 is way too small

**Comment by Serxule** [comment]
also you realize a bunch of other roles get the minigun

**Comment by BadAtThisGame302** [comment]
> 30 is way too small



> also you realize a bunch of other roles get the minigun

I.... don't care about your opinion though... 😃

**Pull request merged**
