### PR TITLE
Adjustments and fixes to maps and Followers

### PR DESCRIPTION
**Pull request by XElectricX**
- Gravestones are anchored
- Cemetery ghoul spawners reduced to 3 that are farther away from the Oasis street to prevent accidental hoards going into town
- Follower basement deleted
- Followers no longer have access to town radio
- Follower armory lost BAR, 14mm SMG, and riot shotgun; gained a hunting and lever action shotgun
- Follower hydroponics has plant data disks again
- Follower dorms has the clothes vendors
- Oasis has beekeeping suits, honey frames, and fly swatters
- Well added next to the tree in Oasis
- Shop no longer has guaranteed Power Armor spawn, replaced with a tier 4 and tier 3 spawner

### CODE REVIEW

**Comment by Cartlord** [comment]
oasis farm also needs honey frames

**Comment by XElectricX** [comment]
> 

Just added.

**Comment by Cartlord** [comment]
Something's wrong. Adding a queen bee to the Oasis farm's apiary deleted the queen without changing the apiary's status. This happened both with and without honey frames being present in the apiary.

**Comment by Serxule** [comment]
>shop with PA spawner

who thought that was a good idea

**Pull request merged**
