### PR TITLE
Revert "Weaponized circuits are commented out"

### PR DESCRIPTION
**Pull request by chemistrymain2**
removing content from the game is bad

i'll rebalance weapon circuits so you can't make pocket rcws later

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
"later" Lol, either rebalance them now or don't uncomment them out unbalanced.

**Comment by AllCorruptingWyrm** [comment]
then give frok time to unbalance and stop going against his wishes.

**Comment by gilvian** [comment]
maybe comment them back in when they get nerfed, let them be commented out for now since there is a high doubt administration will deal with people who abuse those weapons every round

**Comment by BadAtThisGame302** [comment]
> then give frok time to balance* and stop going against his wishes.

What...? Weaponized circuits have been uncommented out since the start of this server, he probably has USED weaponized circuits, he could have nerfed them by now, but he decides to nerf them after I commented them out.

**Comment by SeeminglyTypicalUsername** [comment]
based

**Comment by chemistrymain2** [comment]
> > then give frok time to balance* and stop going against his wishes.
> 
> What...? Weaponized circuits have been uncommented out since the start of this server, he probably has USED weaponized circuits, he could have nerfed them by now, but he decides to nerf them after I commented them out.

i dont know circuits lol

**Pull request closed without merging**
