### PR TITLE
Weather Stuff

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Removes rad storm and fixes some acid rain warnings

## Why It's Good For The Game

Rad storm is broken and I am removing it until I fix it

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
del: Removed rad storm for now
fix: fixed acid rain warnings
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
acid rains also broken (its that green rain right)

**Comment by BadAtThisGame302** [comment]
> acid rains also broken (its that green rain right)

No it's not it was tested.

**Comment by TripleShades** [comment]
It's definitely broken, didn't melt anything on me despite standing in it the whole time.

**Comment by Serxule** [comment]
iunno it hasnt melted or hurt me either, it did the first time but hasnt recently

**Pull request merged**
