### PR TITLE
Factional Martial Arts

### PR DESCRIPTION
**Pull request by CUST-0M**
About The Pull Request

Gives Legion explorers and veterans a krav maga loadout, removes the centurion's CQC and replaces it with a goliath and ups the explorer timelock to ensure less explorer suicide memes. Re-adds the ranger takedown to captain, veteran ranger and all rangers on spawn, applicable to any and all loadouts.

Why It's Good For The Game

Buffs both sides, the Legion a bit more since the NCR already got a fat buff. Plus martial arts is melee stuff which the legion is known for.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: explorer lifegiver and krav maga loadout
add: veteran krav maga loadout (already had lifegiver)
add: captain's ranger takedown on spawn
add: rangers' and vet rangers' ranger takedown on spawn
tweak: centurion's cqc replaced with a goliath

### CODE REVIEW

**Comment by CaputCapital** [comment]
NCR did get a fat buff in the form of hard yards, loadout adjustments, and plans for tweaking/buffing weapons. I don't know about all three explorers having loadouts that give them krav maga. Will it disallow them from using weapons akin to the Fortuna Era Legion Berserker Loadout?

**Comment by BadAtThisGame302** [comment]
> NCR did get a fat buff in the form of hard yards, loadout adjustments, and plans for tweaking/buffing weapons. I don't know about all three explorers having loadouts that give them krav maga. Will it disallow them from using ranged weapons akin to the Fortuna Era Legion Berserker Loadout?

No it won't, because he's giving them krav maga in the MP5 loadout, not a seperate one, and the MP5 is already broken enough, plus he's using base SS13 Krav maga, not changed at all, which can use guns.

**Comment by CUST-0M** [comment]
Added the ranger takedown to the captain and every single ranger with any loadout. No more NCR cope please.
>Krav maga is better.
Yes, it is. Because the Legion is better with melee combat.
The differences between krav maga and the ranger takedown in a real fight is that krav maga can disarm. The rest of the moves are vastly inferior to ranged and melee weaponry.

**Comment by ogrigbe** [comment]
maybe not, too strong, bad bad bad

**Comment by CUST-0M** [comment]
> maybe not, too strong, bad bad bad

not as strong as 16 high damage automatics :^)
anyways if i have to nerf krav maga what should i nerf it to?

**Comment by chemistrymain2** [comment]
> maybe not, too strong, bad bad bad

it's not actually that strong

none of these stun

and they're all worse than just hitting the guy with a machete instead

**Comment by CaputCapital** [comment]
> Added the ranger takedown to the captain and every single ranger with any loadout. No more NCR cope please.
> 
> > Krav maga is better.
> 
> Yes, it is. Because the Legion is better with melee combat. The differences between krav maga and the ranger takedown in a real fight is that krav maga can disarm. The rest of the moves are vastly inferior to ranged and melee weaponry.

This is what I was thinking could be done as balance. The Ranger takedown.

**Comment by CUST-0M** [comment]
Closing this for now since it's contraversial.

**Pull request closed without merging**
