### PR TITLE
Update Pahrump-Underground-1.dmm

### PR DESCRIPTION
**Pull request by DelineFortune**
Enclave bunker

Enclave bunker reworked
Moved things to good places (now you dont need to run whole bunker to check vendors for stims, tools and can do you autistic game with more comfort).
Better cells (for prisonners, because ability to escape is honest)
 
bunker-1

### CODE REVIEW

**Comment by TripleShades** [comment]
Make sure to spin the arcade machines the right way around, they don't look like they are in the preview.

**Comment by BadAtThisGame302** [comment]
Also why is mining so big? Could shorten it a little.

**Comment by DelineFortune** [comment]
image

**Comment by ZAB909** [comment]
Looks good. Maybe put reloading bench ect where the sgts spawn exactly? So you're not running back and forth all the time to the racks, easier if it's just in the middle.

**Pull request merged**
