### PR TITLE
Remaking of Oasis, moves Followers and Den

### PR DESCRIPTION
**Pull request by XElectricX**
Aim of this PR is to not only fix the **badly** mapped town but to make it better than it was. The theme of Oasis in this remake is an inspiration of Megaton with a more homely feel. The Followers clinic has been replaced with a town clinic, and the Followers have been moved elsewhere. Scroll to the end for more on them. Due to the Den being directly below Oasis, it had to be moved to where the old Oasis sewer city was. Accommodated as best as it could be.

### In regards to map edits
Map edits are bad. Stop making unnecessary map edits. All the secure doors, shutters, and buttons in Oasis are now coded in. Only thing map edited are the "strong" iron bars because that should be left for another PR to reduce map edits in Yuma. **Do not make unnecessary map edits to Oasis after I just cleaned it up.**

### Oasis, in pictures
Let's talk about map themes here. Oasis is designed to be a compact, wooden town. The outside walls are metallic for protection, but most of the things inside are made from wood as wood is easier to come by and build with. To travel between levels, there 2 ladders and a staircase in the middle of town. Take the staircase immediately puts you in front of the prospector's shop. You will notice stairs are mostly used in place of ladders now. This is to make it look more like a town, and not some kind of facility.

Upstairs features homes and a metal walkway. One can look around the town from above.

The downstairs sewer city is mostly dilapidated "homes", in addition to the prospector's shop and public workshop. Rather than wood, the majority is metallic and considerably more dirty than the levels above.

_Ground level. The economic and social heart of Oasis._
image

_Upper level. Mostly homes or offices._
image

_The sewer level has become the dilapidated underground of Oasis. Home to the prospector's shop, public workshop, and drug dens._
image

### Gatehouses
The gatehouses now have counters facing the outside so you could still interact with someone if the gates are closed, and intercoms have been added.

_North gatehouse, ground._
image

_North gatehouse, upstairs._
image

_South gatehouse, ground._
image

_South gatehouse, upstairs._
image

### Oasis Store
The town shop has received the biggest makeover. The old design was very invulnerable because most of the merchant's stock was below, where they could not keep an eye on it. It has all been moved into the same room for convenience. Each spawner/item was copied and pasted from the old storage room so more or less the same amount of items remain. The shop also has a drive-thru north of it. Opening the shutters reveals the vending machines lined up. A customer can stop by, browse, buy, leave quickly without even having to come into town. Upstairs is the shopkeeper's apartment, redesigned to not be awful.

_Shopping area and merchandise. Not pictured: vending machines lined up on the drive-thru, covered by the shutters._
image

_Shopkeeper's apartment._
image

### Mayor's Office
To make town meetings look nicer and more convenient, the assembly area was moved right in front of the offices. The speaker can stand in a stage to address the town. The secretary's office is mostly untouched except it has secure door and the chair was moved to actually be in front of the desk. The mayor's office and apartment has been moved around to make use of the space.

_Assembly area, secretary's office, mayor's office._
image

_Mayor's apartment._
image

### Oasis bar
Kitchen had already been remapped by me so it remains mostly the same except for a little bit of space added. The dining area has gained a little bit more space to accommodate the new stage. The upstairs gambling area was made more open and has a slot machine and gambling vendor. The balcony was made smaller and has a decorative garden.

_Kitchen and dining area. Now with a stage!_
image

_Upstairs balcony, gambling hall, and dorms._
image

### Farm
The farm has been left largely unchanged. Compost bin was moved and a bee hive was added. Upstairs was moved more inwards to the town.

_Farm area and farmhouse._
image

_Upstairs farmhouse and balcony._
image

### Local church now inside the actual town
Boggles the mind that it has been right outside the town rather than inside, **and on the Legion side of the gates no less.** The amount of slots has been increased from 1 to 2 to allow for more roleplay opportunities.

_Congregation area and confessions._
image

_Kitchen, balcony with garden, and 2 dorm rooms._
image

### Town Clinic
Followers **as a faction** is not very well made or executed. Their snowflake clinic has been replaced with a MUCH smaller (clinic was so large I even had space for another point of interest, which you will see below) town clinic. It is lower tech in nature to fit the theme of Oasis, reflected in the new wooden architecture and less advanced equipment (except for the return of the pre-war refinery and 2 free advanced scanners).
Upstairs is supplies and a chemistry lab. There is a generous amount of medical supplies since they no longer have their own snowflake farm setup. _There is a farmer role, after all._

The town doctor role itself has 3 slots and a variety of loadouts. Town Doctor loadout is the only one that comes armed and has a bruise pack and stims. The Follower of the Apocalypse loadout is the only one with a medical HUD and comes with synthflesh cans and a first aid kit. The Apothecary loadout has plague doctor clothes and has primitive chem equipment, a box of powders, and a box of poultices. This is meant for those that want to roleplay more low tech healers. The Nurse loadout comes with lollipops, an advanced suture pack, an advanced mesh pack, and a deluxe hypospray.

_Receptions area, operating theatre._
image

_Attic with a large amount of medical supplies and chemistry equipment._
image

### Prospector's Shop
The department has been downsized a lot. More reminiscent of a bunker shop. There is a gear painter in front of the counter.

_Small store and mining equipment room._
image

### Public Workshop

_Remains about the same but with an iron anvil._
image

### Junkyard
New PoI that came out of the space taken up by the giant Followers clinic. Just a normal junkyard, good value for scrappers. Enemies are a mole and roach nest, and a lot of dogs because apparently there is no dog spawner.

image

### Cemetery
New PoI that replaces the old church. Infested with ghouls so be careful not to get too close to the cemetery!

image

### The Great Den Move
Unfortunately to make use of stairs, the Den had to be moved as it was directly beneath Oasis. Sewers rooms were moved around, but in the end there was actually more space made available due to the new under-Oasis being smaller. Have left the empty spaces as rock caverns or empty rooms for whoever wants to add PoIs to them later. The ladder to the Den was moved south next to the old clinic, and the ladder that was there was moved even further south, at the 3 way intersection near the museum.

image

### Followers found a new home
The Followers of the Apocalypse have been moved to the old hospital. The theme for them right now is a converted hospital. The hospital now looks more like a fortress with a community living inside. To show that the Followers have just renovated it, I decided to leave in all the dusty bits except in places that make sense to always stay clean like the operating theatre. The downstairs consists of the lobby, operating theatre/medical storage, chemicals lab, hydroponics, cafeteria, and dorms. The upstairs has an armory, therapist room/holding cell, morgue, and the Administrator's office. Note that the valuable book spawns and combat stim have been moved elsewhere. Be sure to look for them!

_Downstairs._
image

_Upstairs._
image

### The Followers go to war
Since they no longer have the protection of Oasis, the Followers have received some upgrades. The hospital happened to already be made up of map-edited dense rock to look like normal walls (I don't know why???) so I left it like that. The only vulnerable areas are the now reinforced windows in the cafeteria and lobby, and the upstairs windows. The Followers also have a pretty good stock of weapons now.

_No longer pushovers._
image

### CODE REVIEW

**Comment by AllCorruptingWyrm** [comment]
https://www.youtube.com/watch?v=q5Uh0yG0ckM

**Comment by BadAtThisGame302** [comment]
Honestly great PR, the Followers needed to be replaced with the Town Doctor for a while, good work.

**Comment by XElectricX** [comment]
> Gotta say, be a bit careful with the junkyard, scrap is already at large, only thing I would say is advanced scrap is a lacking of, apart from that it looks cool!

I don't salvage nor do I know how it works so if you could explain what drops advanced scrap I can add it. The amount of salvage is probably a lot but I quite like the aesthetic I have right now so I would rather see how much of an effect it is ingame. If it's too much, can be edited easily.

**Comment by Kitsunemitsu** [comment]
Not gonna lie, as much as I hate the followers, this will only piss people off and drive them from the server.

**Comment by ogrigbe** [comment]
Fix your conflicts and I'd also say move the followers out of oasis temporarily and offer them a smaller clinic possibly over by the old school house. I've always hated that spot and its garbage so you're free to delete the entire area and rework a fancy littel clinic for them. We do have a lot of followers mains so at least give that a try first.
image

**Comment by XElectricX** [comment]
> Fix your conflicts and I'd also say move the followers out of oasis temporarily and offer them a smaller clinic possibly over by the old school house. I've always hated that spot and its garbage so you're free to delete the entire area and rework a fancy little clinic for them. We do have a lot of followers mains so at least give that a try first. image

No half measures.

**Comment by XElectricX** [comment]
> Not gonna lie, as much as I hate the followers, this will only piss people off and drive them from the server.

It's literally still the same doctor role, even have a Follower loadout. If you're mad because the illusion of Followers not being part of Oasis was taken down, you probably didn't play Followers for the right reasons.

**Comment by Kitsunemitsu** [comment]
I literally never played followers.
I'm saying that this might piss people off and drive them out.

**Comment by XElectricX** [comment]
> I literally never played followers. I'm saying that this might piss people off and drive them out.

I meant "you" in general, not specifically you as a person. Followers may not be removed though if Rigbe does not budge on it.

**Comment by Cartlord** [comment]
Honestly, I don't see the point of Followers as a faction. If they're to stay, I want them to NOT be inside Oasis any more, because as-is they're just spicy Oasis doctors.

**Comment by XElectricX** [comment]
> Honestly, I don't see the point of Followers as a faction. If they're to stay, I want them to NOT be inside Oasis any more, because as-is they're just spicy Oasis doctors. I ask: what will be lost if they're entirely replaced with Oasis doctors as per this P.R.?

That's the thing, nothing is lost unless you were a volunteer or guard main. In which case, just be a police officer or farmer. But Rigbe seems intent on keeping them so they'll likely be in the old clinic as someone recommended I do.

**Comment by KingMaskito** [comment]
Honestly, just remove public medical roles as a whole if you're doing this. Let the wasters cope if you can't handle doctors actually playing the game.

**Comment by Cartlord** [comment]
What the hell does that even mean, KingMaskito?

**Comment by CaputCapital** [comment]
I wouldn't mind the Followers of the Apocalypse clinic being placed outside of Oasis if they stay.

**Comment by KingMaskito** [comment]
> What the hell does that even mean, KingMaskito?

It means this is a fucking useless change that doesn't solve anything in the game. Honestly, what's the point of removing Followers? What is their ISSUE on the server? What the fuck is up with you people that you think an Oasis doctor would be anymore fun for anyone involved?

**Comment by Cartlord** [comment]
Well, it would mean that
-People don't have to deal with the weird politics of having a faction that's entirely contained within another faction's territory
--The people of Oasis can no longer acquire certain items that're on par with high-tech factions just by asking Followers nicely
-The Oasis farm now has a more definite purpose, rather than being flatly worse than the place across the street's Hydroponics setup

**Comment by Jaaackx** [comment]
Maybe flesh out FOTA loadouts for waster so people can still play them as a 'faction', just without the stupid fucking mega clinic. Make them into the frontier 'Doctors without borders' type they actually appear as in NV.

**Comment by PvtStupidhead** [comment]
Here's my general view of the changes proposed here as a Followers Volunteer player and outside as a farmer, given that I do not believe I have put much time into the Oasis farming given that prior it was an intense and searing pain to perform.

I believe that, as a whole, having the Followers contained within Oasis could've been acceptable had Oasis been on a map akin to Fallout NV: large, and not exactly in the center, both figuratively and literally. Something where they aren't exactly your first go-to for fixing, but rather last when most others have failed. Some of the changes however, while it seems good intended and reasoned, I believe need to be thought about more. The initial reason why soils were given to medicine-boys were to make Xander and Broc given that back in the day, stimfluids didn't exist, and partially now, it's draining on the machines to make and the quantity you get for doing so isn't enough to justify it (and time sink). If they have open-access to the farm (maybe all Oasis roles do, I wouldn't know), then the issue becomes less and it'll be more about pissing off the farmer.

There's still not a grinder in that clinic. Get it a grinder, ffs! People use them all the time and for these people, it'll be crucial if they won't have the DNA Manipulator.

As a general point, in my opinion, this is removing content and condensing the power unto Enclave and Brotherhood more. Remember, Enclave wiped the server out with a bullshit plague nobody could treat because they were the only ones with the machine to figure out what the cure was, and it was the Enclave that used sex chems to give Legion boobs, not the Followers. The Followers of course, are not perfect and have done bullcrap in the past, so it can be justified to remove the plant DNA manipulator to reduce the abuse on that front, but then I'd want an alternative added that's akin to the botanical shears that requires more work to make something happen, either to the doctors or the farmer if they're to take over the role.

And lastly? This pull request seems _extremely_  spiteful towards Followers and if I was a die-hard Follower fan, I'd almost have no faith in you based on how it's written and the topic. My suggestion would be to atleast have it be 'Followers replaced by town doctors', because as it seems you're almost intending on removing the doctor role and continually sprinkling in snowflake or how stupid large it was before will only upset and anger people.

**Comment by chemistrymain2** [comment]
Yes, well, Followers are not being removed. They are being relocated to outside Oasis.

**Comment by AllCorruptingWyrm** [comment]
if they're being removed relocate them by the old BoS village or something.

**Comment by chemistrymain2** [comment]
Otherwise:

1. You've made the shop very small, which is not ideal, both for moving around in and that you seem to have reduced the number of resources they get. It's rather cramped.

It is best you leave the shop as-is, more or less.

2. You've made the mayor and secretary's offices a little smaller than normal.

3. Bar kitchen is incredibly tiny.


4. You've shrunk the Bar balcony.


5. The doctor's clinic is quite ugly and randomly placed. There's no dedicated operating table or room-this is virtually designed, more or less, to be a room where people run into for free heals and then leave. It is cramped (bad, large is better), ugly looking (randomly placed tables, items on stacks), et cetera. I can't imagine anyone would want to stay inside for very long.


6. In regard to housing, there just isn't a lot of it. It may be in your interest to just expand the size of Oasis and add more direct housing, because eugh. There aren't any citizen houses. The ones downstairs barely count as sex shacks.


7. Prospector shrunk and nerfed in the process.


8. Personal peeve: How brown everything is. God damn, would it kill you to use the shopkeeper or mayor's wooden tiles instead? Everything is brown to the point it hurts my eyes.

**Comment by XElectricX** [comment]
> Here's my general view of the changes proposed here as a Followers Volunteer player and outside as a farmer, given that I do not believe I have put much time into the Oasis farming given that prior it was an intense and searing pain to perform.
> 
> I believe that, as a whole, having the Followers contained within Oasis could've been acceptable had Oasis been on a map akin to Fallout NV: large, and not exactly in the center, both figuratively and literally. Something where they aren't exactly your first go-to for fixing, but rather last when most others have failed. Some of the changes however, while it seems good intended and reasoned, I believe need to be thought about more. The initial reason why soils were given to medicine-boys were to make Xander and Broc given that back in the day, stimfluids didn't exist, and partially now, it's draining on the machines to make and the quantity you get for doing so isn't enough to justify it (and time sink). If they have open-access to the farm (maybe all Oasis roles do, I wouldn't know), then the issue becomes less and it'll be more about pissing off the farmer.
> 
> There's still not a grinder in that clinic. Get it a grinder, ffs! People use them all the time and for these people, it'll be crucial if they won't have the DNA Manipulator.
> 
> As a general point, in my opinion, this is removing content and condensing the power unto Enclave and Brotherhood more. Remember, Enclave wiped the server out with a bullshit plague nobody could treat because they were the only ones with the machine to figure out what the cure was, and it was the Enclave that used sex chems to give Legion boobs, not the Followers. The Followers of course, are not perfect and have done bullcrap in the past, so it can be justified to remove the plant DNA manipulator to reduce the abuse on that front, but then I'd want an alternative added that's akin to the botanical shears that requires more work to make something happen, either to the doctors or the farmer if they're to take over the role.
> 
> And lastly? This pull request seems _extremely_ spiteful towards Followers and if I was a die-hard Follower fan, I'd almost have no faith in you based on how it's written and the topic. My suggestion would be to atleast have it be 'Followers replaced by town doctors', because as it seems you're almost intending on removing the doctor role and continually sprinkling in snowflake or how stupid large it was before will only upset and anger people who genuinely believe it was correct or those who acted reasonably by grouping them all in.

You a lot of good points. However, Followers are being kept anyways so none of these are a concern. Town doctor can still mass produce stimfluid, I've done it with a basic chem dispenser (but with a pico). Even have a recharger if they run out of energy. I call the clinic snowflake because it's a tiny, more advanced city within an another one. They had no reason to have their own BoS-tier hydroponics, a dining area, 2 offices, a balcony, a morgue, dorms, and a bunch of other rooms. Now since it's just being moved outside the town some of these make sense to keep.

**Comment by XElectricX** [comment]
> Otherwise:
> 
> 1. You've made the shop very small, which is not ideal, both for moving around in and that you seem to have reduced the number of resources they get. It's rather cramped.
> 
> It is best you leave the shop as-is, more or less.
> 
> 2. You've made the mayor and secretary's offices a little smaller than normal.
> 3. Bar kitchen is incredibly tiny.
> 4. You've shrunk the Bar balcony.
> 5. The doctor's clinic is quite ugly and randomly placed. There's no dedicated operating table or room-this is virtually designed, more or less, to be a room where people run into for free heals and then leave. It is cramped (bad, large is better), ugly looking (randomly placed tables, items on stacks), et cetera. I can't imagine anyone would want to stay inside for very long.
> 6. In regard to housing, there just isn't a lot of it. It may be in your interest to just expand the size of Oasis and add more direct housing, because eugh. There aren't any citizen houses. The ones downstairs barely count as sex shacks.
> 7. Prospector shrunk and nerfed in the process.
> 8. Personal peeve: How brown everything is. God damn, would it kill you to use the shopkeeper or mayor's wooden tiles instead? Everything is brown to the point it hurts my eyes.

The town should be more compact and brown, yes. The theme is a frontier town. The only places you'll notice are bigger than necessary are social areas. I've tried to copy and paste each resource pile/spawner/item into the new shop to try to match the amount there used to be. Also, did you not notice the operating theatre right next to the counter?

**Comment by KingMaskito** [comment]
> They had no reason to have their own BoS-tier hydroponics, a dining area, 2 offices, a balcony, a morgue, dorms, and a bunch of other rooms. Now since it's just being moved outside the town some of these make sense to keep.

You've obviously never played a medical role for longer than a round if you really think none of these things matter or "are snowflakey" to have. It's as if you're writing from the perspective of someone who thinks a doctors only job is to sit down with their thumbs up their asses and heal people that waltz in. It's obvious from the way you designed the Oasis Doctors clinic and it's obvious from the antagonistic tone you speak about the Followers with. The only thing this though process does though is reduce them to the boring healslut, vanilla ss13 medbay role that so many people ALREADY hate some of the less educated Followers for being. 

Keep the roleplay spaces, keep the optional mechanical spaces like botany for them to futz about with when not healing, and keep the damn role fun. Though again, it's pretty clear you don't care about their fun as it stands.

**Comment by Cartlord** [comment]
If the Followers are going to have a Hydroponics space, they should not be in Oasis, a town that has three Farmer slots.

**Comment by BadAtThisGame302** [comment]
I liked this for the Follower removal.... you've changed...

**Comment by XElectricX** [comment]
> I liked this for the Follower removal.... you've changed...

Forward your complaint to Rigbe.

**Comment by Cartlord** [comment]
YOU FORGOT TO ADD BEEKEEPER SUITS

**Pull request merged**
