### PR TITLE
Nerfs the Vendor, the Khans and the Den because of people like this

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

image

## Why It's Good For The Game

The Khans use the C4 to abuse the casino, that's gone. They use some chemical reaction to get rich from the gold bars from the vendor, that's gone. They use med-x to get rich from the vendor, that's gone. Wow man what a good faction bro! Riveting stuff.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog

:cl:
del: Removed the C4 from the Khan and Den gang tool
balance: rebalanced the vendor buying ore price
fix: fixed the med-x price buff I forgot
/:cl:

### CODE REVIEW

**Comment by Zebraman** [comment]
>Khans
>Post a screenshot of the Den
Ok retard.

**Comment by BadAtThisGame302** [comment]
> > Khans
> > Post a screenshot of the Den
> > Ok retard.

Sorry man, my bad, 🧎🏻‍♂️

**Comment by BadAtThisGame302** [comment]
Fixed @Zebraman

**Comment by Zebraman** [comment]
I see but I fear you forgot to comment my dick out of ya mama's mouth @BadAtThisGame302

**Comment by AllCorruptingWyrm** [comment]
the den gangtool is broken lmao
just letting you know, its out of scope for me

**Comment by CocaColaTastesGood** [comment]
The vendor doesn't reflect these changes in price. Why not remove the reagent that allowed gold to be created rather than nerfing the price of gold?

**Pull request merged**
