### PR TITLE
Yuma - Old Town Town/Map Rework

### PR DESCRIPTION
**Pull request by Basinger1178**
## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added two buildings north of oasis. (Library on the right, and a little gun store for non townies to take over for themselves).
add: Added a cave mini-dungeon for botany/tribal mains, as well as a little area near ncr that help fills in some emptiness.
del: Removed old things

/:cl:

### CODE REVIEW

**Comment by ZAB909** [comment]
My brother in christ can we not have 15 super mutants, half being elites, with basically no loot, in viewing distance of the main civilian town's entrance?

**Comment by gilvian** [comment]
My brother in Christ, what the fuck is wrong with you?

image
You put in multiple super mutants and nightkin next to oasis for no reason, having to kill nightkin elite, something that can 2 shot you without good armour just to get raider tier armour or THIS
image
and last offence is that it just looks ugly and unoriginal, the old structures were not atleast squares and had possibility to have bases in them like people have been building but now its just boring square with no reason to fix just kill the super mutants and get the loot, but also fun fact, those walls are weldable 
image
so who cares I suppose

**Comment by gilvian** [comment]
image
also that area for "tribals/botanists"

why

**Comment by ZAB909** [comment]
No merge pls rigbe this pr is too wild

**Comment by ogrigbe** [comment]
it tis a little wild my man, lets hold off on this.

**Pull request closed without merging**
