### PR TITLE
Update plasmaf13.dm firedelay to be 20% less bad and 25% less slowdown

### PR DESCRIPTION
**Pull request by Pokebutt**
## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
No? Plasma doesn't need a buff.

**Comment by Pokebutt** [comment]
> No? Plasma doesn't need a buff.

the rifle does not the actual weapon the fire rate is atrocious

**Comment by DaemonTinadel** [comment]
The reason why the rifle fires slow is because its strong. It doesnt need a buff.

**Comment by chemistrymain2** [comment]
This is fine, actually.

Plasma is surprisingly weak. The fire rate can be tweaked-the slowdown is also immense, considering that most automatics only slow you by, like... .3.

**Pull request merged**
