### PR TITLE
Ncr base rework 4/10/22

### PR DESCRIPTION
**Pull request by KillerGryphon**
## About The Pull Request

I made this NCR base before the 2nd floors came into being, but now they are here, it's time for an update! New areas have been added, prison and armory places have swapped, and NCR now has 2nd floors most importantly. I will likely work on the gates later, also in need of an overhaul.

NCR base 4-10-22

NCR base above 4-10-22
05.PNG)

## Why It's Good For The Game

Keeps the NCR base from falling too far behind in terms of content and updates.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by KillerGryphon** [comment]
If you have any comments or concerns, lemme know, always open to changing something, just give me details!

**Comment by SeeminglyTypicalUsername** [comment]
Put secret documents in the war room and make the officer's offices a little larger

**Comment by ogrigbe** [comment]
Get some votes and I'll put this in.

**Comment by KillerGryphon** [comment]
Alright, made some changes! 

New NCR gate house

NCR gatehouse above
 As you can see, new NCR gatehouse! The original gatehouse was to test out how the NCR dealt with not having to look south to fight, but that didn't work out, so we're back to this format. I have moved the secret documents to the war room, and added a firing range nook by the pond, as well as adjusting the sizes of the officer offices ever so slightly to make them larger.

**Comment by KillerGryphon** [comment]
> Can you revert the gates and set up preset defenses instead?

I honestly have no clue what this is meant to mean, I talked a little in the discord about it too and that phrase came up, and I'm still not sure what exactly that entails.

**Comment by KillerGryphon** [comment]
Anyhoo, I have now put the armory on top of the prison, added a med center and bathroom on top of the medbay, and added bunks where the armory used to be, with a basketball court on top. NCR is **_NOW BALLIN'_**
NCR base 4-12-22
NCR base above 4-12-22

**Comment by ogrigbe** [comment]
Please do one more and I will merge this first, fix your conflicts. Sorry for messing with it so much with all the other PR's.

**Pull request merged**
