### PR TITLE
Tweaking and sprite fixes

### PR DESCRIPTION
**Pull request by Legate-Maxson**
## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
Sprite fixes, Centurion loadout changes, M1919 buff, P90 bug fix, Buffs Salvaged PA speed, Slightly Nerfs Working PA speed
/:cl:

TheLastItalianSupper

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Why are you giving an RCW to the centurion?

**Comment by DaemonTinadel** [comment]
Because the m1919 is horrible, The Palacent used to get an aer12 and then was given the m1919 which wasnt bad before full auto but after it was completely garbage and no1 fixed it. Fiends get RCWs i dont think a Centurion getting one is anything  wild.

**Comment by BadAtThisGame302** [comment]
> Because the m1919 is horrible, The Palacent used to get an aer12 and then was given the m1919 which wasnt bad before full auto but after it was completely garbage and no1 fixed it. Fiends get RCWs i dont think a Centurion getting one is anything wild.

A Centurion getting one with current hitscan and VERY low laser armor protection all around will be bad, plus the M1919 is now auto instead of what it previously was.

**Comment by Legate-Maxson** [comment]
> > Because the m1919 is horrible, The Palacent used to get an aer12 and then was given the m1919 which wasnt bad before full auto but after it was completely garbage and no1 fixed it. Fiends get RCWs i dont think a Centurion getting one is anything wild.
> 
> A Centurion getting one with current hitscan and VERY low laser armor protection all around will be bad, plus the M1919 is now auto instead of what it previously was.

The AER12 has pen as well as damage. The M1919 is now a true auto weapon and the RCW has no extra pen. It allows the Centurion to actually be scary but be weak agaisn't high armor targets such as the Vet Ranger and NCR Heavy

**Comment by BadAtThisGame302** [comment]
> > > Because the m1919 is horrible, The Palacent used to get an aer12 and then was given the m1919 which wasnt bad before full auto but after it was completely garbage and no1 fixed it. Fiends get RCWs i dont think a Centurion getting one is anything wild.
> > 
> > 
> > A Centurion getting one with current hitscan and VERY low laser armor protection all around will be bad, plus the M1919 is now auto instead of what it previously was.
> 
> The AER12 has pen as well as damage thus it couldnt be readded. The M1919 is now a true auto weapon and the RCW has no extra pen. It allows the Centurion to actually be scary but be weak against high armor targets such as the Vet Ranger and NCR Heavy. I did not want to include the new M1919 on the highest armor armor the Centurion can get.

The M1919 was moved to the Palahunter due to it being tanky and him having the LMG would fit quite well, I remember previously there's been other attemps to give the Palahunter a laser gun of some sort but they all were closed down to being too OP. Especially I personally think the RCW with a higher firing speed than the AER12 would cause more damage than the rather slow firing AER12.

**Comment by Legate-Maxson** [comment]
The RCW is absolute shit against high armor targets. It was tested by multiple people its less of an issue then the AER12. The palacent already gets the Goliath which is already absurdly strong. Giving strength to the frontline centurion allowing players chose a loadout not based on a powerful sniper or a powerful melee. The Regular Centurion being the mid range power house is great.

**Comment by DaemonTinadel** [comment]
The RCW is not better than an AER12. Again the Paladin used to have an aer12 until lonestar. The fact that palacent is a heavy class doesnt mean that it should have a heavy fucking weapon.

**Comment by chemistrymain2** [comment]
> > > Because the m1919 is horrible, The Palacent used to get an aer12 and then was given the m1919 which wasnt bad before full auto but after it was completely garbage and no1 fixed it. Fiends get RCWs i dont think a Centurion getting one is anything wild.
> > 
> > 
> > A Centurion getting one with current hitscan and VERY low laser armor protection all around will be bad, plus the M1919 is now auto instead of what it previously was.
> 
> The AER12 has pen as well as damage thus it couldnt be readded. The M1919 is now a true auto weapon and the RCW has no extra pen. It allows the Centurion to actually be scary but be weak against high armor targets such as the Vet Ranger and NCR Heavy. I did not want to include the new M1919 on the highest armor armor the Centurion can get.

please do not add the rcw until laser armor is buffed as it is hilariously overpowered right now

**Comment by chemistrymain2** [comment]
> The RCW is not better than an AER12. Again the Paladin used to have an aer12 until lonestar. The fact that palacent is a heavy class doesnt mean that it should have a heavy fucking weapon.

yeah the paladin used to have an aer12 until lonestar when it was removed from the paladin when laser weapons were made hitscan and armor was toned down and now the aer12 is weaker than the rcw is against most targets

**Pull request closed without merging**
