### PR TITLE
Enclave Private and Sergeant get laser rifles as standard

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

Privates and Sergeants get AER9s instead of the assault carbine and R91.

Also renames the "American Citizen" role to "U.S. Citizen" to be correct.

## Why It's Good For The Game

Despite what some people will say, balance.

At the moment the entire BoS gets laser rifles as standard so this isn't that big of a change balance-wise.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by chemistrymain2** [comment]
This is fine, seeing that AER9s are weaker than assault carbines.

**Comment by chemistrymain2** [comment]
Actually, it removes the gammagun. Do not merge.

**Comment by chemistrymain2** [comment]
Now you can merge.

**Comment by SeeminglyTypicalUsername** [comment]
Can you make it a loadout

**Pull request closed without merging**
