### PR TITLE
Fixes pref bug that broke succubus milk and similar chems

### PR DESCRIPTION
**Pull request by biotear**
## About The Pull Request

When I ported the chems, I didn't notice the toggle they used didn't exist here, which made them not work. Now they're tied to the arousal toggle.

## Why It's Good For The Game

Working as intended now = good

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by ogrigbe** [comment]
Maybe, but your code is conflicted

**Comment by BadAtThisGame302** [comment]
Why are you trying to re-add in Zombie Powder, Eigenstasium, the Clone chem and some shock chem **undocumented?**

**Comment by Doru-7** [comment]
Finally, some good fucking milk.

Also, can anyone find the conflict? Is it conflicting with the code that added these chems in the first place?

**Comment by biotear** [comment]
> Why are you trying to re-add in Zombie Powder, Eigenstasium, the Clone chem and some shock chem **undocumented?**

they were already added in, this is conflicting with what did because github is doing some fuckery.

**Comment by biotear** [comment]
> Maybe, but your code is conflicted

it's conflicting with my last PR, the master branch isn't updated to include it for some reason, at least it isn't when I fetch origin.

**Comment by Doru-7** [comment]
We've lost a powerful addition today... a fatal blow to hornycoders

**Pull request closed without merging**
