### PR TITLE
gives legion legate a bag

### PR DESCRIPTION
**Pull request by BobNewman-max**
## About The Pull Request

gives legate a bag.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by gilvian** [comment]
image
hmmm

**Comment by AndriyKatsubo** [comment]
With additional CQC, 4x bitters, and binoculars? =)

**Comment by Hadoje** [comment]
Okay but can we give legate gear wound protection?

**Comment by BobNewman-max** [comment]
> Okay but can we give legate gear wound protection?

no.

**Comment by BobNewman-max** [comment]
> With additional CQC, 4x bitters, and binoculars? =)

yup, its admin-spawn only so. Yes. Give them gear. I see 0 reason as to why this shouldn't happen.

Get ready for my next PR by the way, it'll break atmos and it'll also involve CQC Cent.

**Comment by BadAtThisGame302** [comment]
> With additional CQC, 4x bitters, and binoculars? =)

It's an admin spawn role, who cares.

**Comment by BobNewman-max** [comment]
will say, the entire point of this is to stop admins spawning in as legate x-y-z then giving themselves some high tier ass fucking gun that makes 0 sense for them to have (var.edit guns) and then losing it in-round and some random waster being bwoinked for it, that and if they fail at any time, its aids. Another point.

Legate spawning in takes 10 mins to do, why? Because you need to spawn meds, ammo, bag, guns, other gear, then. You need to do whatever it is you need to do. This gives admins a quicker response. 

But primarily? It allows the admins to spawn in more often without worrying about constant shitter setups and adminbus out the ass. Because this time, its logical. legate is powerful as fuck? EPIC.

**Pull request merged**
