### PR TITLE
FEV types

### PR DESCRIPTION
**Pull request by EgorDinamit**
## About The Pull Request

- Adds 2 new FEV types: FEV-II and Curling-13.
- Refactors code for the FEV slightly.
- FEV-I can no longer ghoulify you into a normal ghoul.
- The loot table that had FEV previously now may contain FEV-II as well.

## Why It's Good For The Game

- FEV-II turns you into a super mutant as long as your radiation level is safe(<500). Curling-13 does something similar, except as we all know, its purpose is to kill people. I didn't add Curling-13 anywhere, so for now it will remain an admin item for events and such.
- Just what it says, code cleanup. I also made it a bit easier to cure FEV(From 2% to 5%).
- It kind of sucked how you could end up as a basic ghoul with FEV.
- A fun item added to very rare loot drop. That's just that. Also made it slightly less rare(From 1 to 2. All other items have a weight of 5).

## Pre-Merge Checklist

- [x] You documented all of your changes.
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
Egor with the Enclave buffs... as always...

**Comment by EgorDinamit** [comment]
> Egor with the Enclave buffs... as always...

Enclave doesn't even get FEV? :raised_eyebrow:

**Comment by Refined1** [comment]
Egor with the Enclave buffs... as always...

**Comment by Pokebutt** [comment]
> ## About The Pull Request
> * Adds 2 new FEV types: FEV-II and Curling-13.
> * Refactors code for the FEV slightly.
> * FEV-I can no longer ghoulify you into a normal ghoul.
> * The loot table that had FEV previously now may contain FEV-II as well.
> 
> ## Why It's Good For The Game
> * FEV-II turns you into a super mutant as long as your radiation level is safe(<500). Curling-13 does something similar, except as well all know, its purpose is to kill people. I didn't add Curling-13 anywhere, so for now it will remain an admin item for events and such.
> * Just what it says, code cleanup. I also made it a bit easier to cure FEV(From 2% to 5%).
> * It kind of sucked how you could end up as a basic ghoul with FEV.
> * A fun item added to very rare loot drop. That's just that. Also made it slightly less rare(From 1 to 2. All other items have a weight of 5).
> 
> ## Pre-Merge Checklist
> * [x]  You documented all of your changes.
> * [x]  You tested this on a local server.
> * [x]  This code did not runtime during testing.

I could see this work as a solution for super mutant players so admins dont have to force it

**Comment by EgorDinamit** [comment]
> I could see this work as a solution for super mutant players so admins dont have to force it

Exactly, although chances are you won't be able to reliably find FEV-II at the moment.

**Pull request merged**
