### PR TITLE
Centurion CQC removal, replaced. (Requested by Enclave players)

### PR DESCRIPTION
**Pull request by Refined1**
Centurion CQC removal, replaced. (Not?)

## About The Pull Request
It replaces CQC with another martial art that is kinda like Krav Maga but with a few touches of carp.

## Why It's Good For The Game
After a recent raid between the NCR/Enclave and the Legion we discussed how we could possibly make the Centurion less op and unfun to play against. A few of the Enclave players suggested that it'd be better if he had Rbass instead of CQC so I thought, "Sure, maybe it'll work." So here we are, replacing CQC with another martial art. 

## Pre-Merge Checklist

- [ x] You tested this on a local server.
- [x ] This code did not runtime during testing.
- [x ] You documented all of your changes.

## Changelog

:cl:
add: Rbass for Cent
Removed: CQC for cent
/:cl:

### CODE REVIEW

**Comment by Refined1** [comment]
WOW WHAT A NICE PR, RIGBE SHOULD MERGE THIS ONE! - Tenias (Discord: tenias#2089)

**Comment by panzerr1944** [comment]
rbass is stronger cqc moment lmfao

**Comment by thart02** [comment]
>buffs centurion cqc
lmao

**Comment by Refined1** [comment]
I'd like to clarify that this was requested by Enclave players after they lost to Cent CQC. :(

**Comment by CUST-0M** [comment]
This is pretty alright, but I will be downvoting it due to it being requested by enclave players. I'd reccomend re-coloring the APA sprite hot pink and giving it a chastity belt before you merge this.

**Comment by Legate-Maxson** [comment]
Shitpost PR

**Comment by AllCorruptingWyrm** [comment]
mom said its my turn to remove cqc

**Comment by chemistrymain2** [comment]
well, i the enclave requested it

oh they did actually

hee hee ok merge

**Comment by BadAtThisGame302** [comment]
I approve of the PR as it was suggested by the players to a replacement of CQC

**Comment by thart02** [comment]
The problem with this PR is that it literally just buffs the cent. Rbass is more powerful than CQC, and is from base ss13, and is a traitor attack, that can only really be handled by a bunch of people throwing chairs at the user. The problem further is that with instant healing, like in f13, it's even more broken

**Comment by LocalizedDownpour** [comment]
> The problem with this PR is that it literally just buffs the cent. Rbass is more powerful than CQC, and is from base ss13, and is a traitor attack, that can only really be handled by a bunch of people throwing chairs at the user. The problem further is that with instant healing, like in f13, it's even more broken

CQC is Also from base ss13...you know that right?

**Comment by chemistrymain2** [comment]
> > The problem with this PR is that it literally just buffs the cent. Rbass is more powerful than CQC, and is from base ss13, and is a traitor attack, that can only really be handled by a bunch of people throwing chairs at the user. The problem further is that with instant healing, like in f13, it's even more broken
> 
> CQC is Also from base ss13...you know that right?

Of course we do. That's why we added it-it's because it's funny.

While I'd be fine removing it to make a centurion player I don't like very angry, I have a better solution in mind.

**Comment by Starfirejordan** [comment]
just no. i rather fight CQC then bullet deflecting ninja

**Comment by thart02** [comment]
> > The problem with this PR is that it literally just buffs the cent. Rbass is more powerful than CQC, and is from base ss13, and is a traitor attack, that can only really be handled by a bunch of people throwing chairs at the user. The problem further is that with instant healing, like in f13, it's even more broken
> 
> CQC is Also from base ss13...you know that right?

Yeah that's why it needs to be removed.
replacing it doesn't SOLVE the issue

**Pull request closed without merging**
