### PR TITLE
Bos buff, makes Storm drum usable

### PR DESCRIPTION
**Pull request by Legate-Maxson**
As Frok and I discussed we cannot leave other factions behind, So we gave one knight loadout an MP5 and gave the Head Paladin back their G11 and the Senior Paladin their WT-550 SMG

I also added the ability to print Stick mags from the ammolathe since the Whitelegs stormdrum can only use stick mags. The weapon is now useable. 

Combat Rifle re-added to the loot pool

### CODE REVIEW

**Comment by Legate-Maxson** [comment]
> As Frok and I discussed we cannot leave other factions behind, So we gave one knight loadout an MP5 and gave the Head Paladin back their G11 and the Senior Paladin their WT-550 SMG
> 
> I also added the ability to print Stick mags from the ammolathe since the Whitelegs stormdrum can only use stick mags. The weapon is now useable.
> 
> Removed Combat rifle from the loot pool for now.

**Comment by chemistrymain2** [comment]
acceptable pr

**Comment by AllCorruptingWyrm** [comment]
inshallah where is the Enclave buff.

**Comment by Snowyypanda** [comment]
i would like for the ncr base to get an overhaul, a whole redesign so it's coherent with the rangers base cause as of now the base seems all over the place

**Comment by BadAtThisGame302** [comment]
> i would like for the ncr base to get an overhaul, a whole redesign so it's coherent with the rangers base cause as of now the base seems all over the place

Make a complaint in the mapping channel in the discord, not on the Brotherhood buff PR

**Comment by BadAtThisGame302** [comment]
> i would like for the ncr base to get an overhaul, a whole redesign so it's coherent with the rangers base cause as of now the base seems all over the place

Make a complaint in the mapping channel in the discord, not on the Brotherhood buff PR

**Pull request merged**
